// <auto-generated />
using System;
using LeboncoinAPI.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeboncoinAPI.Migrations
{
    [DbContext(typeof(LeboncoinDBContext))]
    [Migration("20260311121339_migration-v1.0.1")]
    partial class migrationv101
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdresseId"));

                    b.Property<string>("NomRue")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("nomrue");

                    b.Property<int?>("NumeroRue")
                        .HasColumnType("integer")
                        .HasColumnName("numerorue");

                    b.Property<int>("VilleId")
                        .HasColumnType("integer")
                        .HasColumnName("idville");

                    b.HasKey("AdresseId");

                    b.HasIndex("VilleId");

                    b.ToTable("adresse", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.Property<int>("AnnonceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AnnonceId"));

                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    b.Property<int?>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<string>("DescriptionAnnonce")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descriptionannonce");

                    b.Property<bool>("EstVerifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estverifie");

                    b.Property<int>("HeureArriveeId")
                        .HasColumnType("integer")
                        .HasColumnName("idheurearrivee");

                    b.Property<int>("HeureDepartId")
                        .HasColumnType("integer")
                        .HasColumnName("idheuredepart");

                    b.Property<string>("LienPhoto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lienphoto");

                    b.Property<int?>("MinimumNuitee")
                        .HasColumnType("integer")
                        .HasColumnName("minimumnuitee");

                    b.Property<decimal?>("MontantAcompte")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("montantacompte");

                    b.Property<int?>("NbChambres")
                        .HasColumnType("integer")
                        .HasColumnName("nbchambres");

                    b.Property<int?>("NombreBebesMax")
                        .HasColumnType("integer")
                        .HasColumnName("nombrebebesmax");

                    b.Property<int?>("NombreEtoilesLeBonCoin")
                        .HasColumnType("integer")
                        .HasColumnName("nombreetoilesleboncoin");

                    b.Property<bool>("PossibiliteAnimaux")
                        .HasColumnType("boolean")
                        .HasColumnName("possibiliteanimaux");

                    b.Property<bool>("PossibiliteFumeur")
                        .HasColumnType("boolean")
                        .HasColumnName("possibilitefumeur");

                    b.Property<int?>("PourcentageAcompte")
                        .HasColumnType("integer")
                        .HasColumnName("pourcentageacompte");

                    b.Property<decimal>("PrixNuitee")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("prixnuitee");

                    b.Property<bool>("SmsVerifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("smsverifie");

                    b.Property<string>("TitreAnnonce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("titreannonce");

                    b.Property<int>("TypeHebergementId")
                        .HasColumnType("integer")
                        .HasColumnName("idtypehebergement");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.HasKey("AnnonceId")
                        .HasName("pk_annonce");

                    b.HasIndex("AdresseId");

                    b.HasIndex("DateId");

                    b.HasIndex("HeureArriveeId");

                    b.HasIndex("HeureDepartId");

                    b.HasIndex("TypeHebergementId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("annonce", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("AvisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idavis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvisId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<decimal>("NombreEtoiles")
                        .HasColumnType("decimal(2,1)")
                        .HasColumnName("nombreetoiles");

                    b.Property<string>("TexteAvis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texteavis");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.HasKey("AvisId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("avis", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("CategorieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategorieId"));

                    b.Property<string>("NomCategorie")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("nomcategorie");

                    b.HasKey("CategorieId");

                    b.ToTable("categorie", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Commodite", b =>
                {
                    b.Property<int>("CommoditeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcommodite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommoditeId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    b.Property<string>("NomCommodite")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomcommodite");

                    b.HasKey("CommoditeId");

                    b.HasIndex("CategorieId");

                    b.ToTable("commodite", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Compensation", b =>
                {
                    b.Property<int>("CompensationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcompensation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompensationId"));

                    b.Property<string>("NomCompensation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomcompensation");

                    b.HasKey("CompensationId");

                    b.ToTable("compensation", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.DateReference", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DateId"));

                    b.Property<DateTime?>("DateValeur")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("DateId");

                    b.ToTable("date", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.Property<int>("DepartementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddepartement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartementId"));

                    b.Property<string>("NomDepartement")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nomdepartement");

                    b.Property<string>("NumeroDepartement")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("numerodepartement");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer")
                        .HasColumnName("idregion");

                    b.HasKey("DepartementId");

                    b.HasIndex("RegionId");

                    b.ToTable("departement", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Heure", b =>
                {
                    b.Property<int>("HeureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idheure");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HeureId"));

                    b.Property<TimeSpan>("HeureValeur")
                        .HasColumnType("time")
                        .HasColumnName("heure");

                    b.HasKey("HeureId");

                    b.ToTable("heure", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idincident");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncidentId"));

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<string>("DescriptionIncident")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descriptionincident");

                    b.Property<bool>("EstClasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estclasse");

                    b.Property<bool>("EstRembourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estrembourse");

                    b.Property<bool>("EstRemisAuContentieux")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estremisaucontentieux");

                    b.Property<int>("Etape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("etape");

                    b.Property<string>("ExplicationProprietaire")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explicationproprietaire");

                    b.Property<string>("MotifIncident")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motifincident");

                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.HasKey("IncidentId")
                        .HasName("pk_incident");

                    b.HasIndex("DateId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("incident", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmessage");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MessageId"));

                    b.Property<string>("ContenuMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contenumessage");

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("UtilisateurExpediteurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateurexpediteur");

                    b.Property<int>("UtilisateurReceveurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateurreceveur");

                    b.HasKey("MessageId");

                    b.HasIndex("UtilisateurExpediteurId");

                    b.HasIndex("UtilisateurReceveurId");

                    b.ToTable("message", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Particulier", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("civilite");

                    b.Property<int>("DateNaissanceId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomutilisateur");

                    b.Property<string>("PrenomUtilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomutilisateur");

                    b.HasKey("UtilisateurId");

                    b.ToTable("particulier", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Professionnel", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomsociete");

                    b.Property<decimal>("NumSiret")
                        .HasColumnType("numeric(14)")
                        .HasColumnName("numsiret");

                    b.Property<string>("SecteurActivite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secteuractivite");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("NumSiret")
                        .IsUnique();

                    b.ToTable("professionnel", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idregion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<string>("NomRegion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomregion");

                    b.HasKey("RegionId");

                    b.ToTable("region", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("AnnonceId")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int>("DateDebutId")
                        .HasColumnType("integer")
                        .HasColumnName("iddatedebutreservation");

                    b.Property<int>("DateFinId")
                        .HasColumnType("integer")
                        .HasColumnName("iddatefinreservation");

                    b.Property<string>("NomClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomclient");

                    b.Property<string>("PrenomClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomclient");

                    b.Property<string>("TelephoneClient")
                        .HasColumnType("char(10)")
                        .HasColumnName("telephoneclient");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.HasKey("ReservationId");

                    b.HasIndex("AnnonceId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("reservation", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.TypeHebergement", b =>
                {
                    b.Property<int>("TypeHebergementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypehebergement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeHebergementId"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    b.Property<string>("NomTypeHebergement")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomtypehebergement");

                    b.HasKey("TypeHebergementId");

                    b.HasIndex("CategorieId");

                    b.ToTable("typehebergement", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.TypeVoyageur", b =>
                {
                    b.Property<int>("TypeVoyageurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypevoyageur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeVoyageurId"));

                    b.Property<string>("NomTypeVoyageur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomtypevoyageur");

                    b.HasKey("TypeVoyageurId");

                    b.ToTable("typevoyageur", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UtilisateurId"));

                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    b.Property<int>("DateId")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<bool>("IdentityVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("identity_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_path");

                    b.Property<string>("Pseudonyme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pseudonyme");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("remember_token");

                    b.Property<decimal>("Solde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("solde");

                    b.Property<string>("TelephoneUtilisateur")
                        .IsRequired()
                        .HasColumnType("char(10)")
                        .HasColumnName("telephoneutilisateur");

                    b.Property<DateTime?>("TwoFactorConfirmedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("two_factor_confirmed_at");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_recovery_codes");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("UtilisateurId")
                        .HasName("pk_utilisateur");

                    b.HasIndex("AdresseId");

                    b.HasIndex("DateId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_utilisateur_email");

                    b.HasIndex("TelephoneUtilisateur")
                        .IsUnique()
                        .HasDatabaseName("uq_utilisateur_telephone");

                    b.ToTable("utilisateur", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.Property<int>("VilleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idville");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VilleId"));

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasColumnType("char(5)")
                        .HasColumnName("codepostal");

                    b.Property<int>("DepartementId")
                        .HasColumnType("integer")
                        .HasColumnName("iddepartement");

                    b.Property<string>("NomVille")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nomville");

                    b.Property<decimal>("TaxeDeSejour")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("taxedesejour");

                    b.HasKey("VilleId");

                    b.HasIndex("DepartementId");

                    b.ToTable("ville", "public");
                });

            modelBuilder.Entity("demander", b =>
                {
                    b.Property<int>("idincident")
                        .HasColumnType("integer");

                    b.Property<int>("idcompensation")
                        .HasColumnType("integer");

                    b.HasKey("idincident", "idcompensation")
                        .HasName("pk_demander");

                    b.HasIndex("idcompensation");

                    b.ToTable("demander", "public");
                });

            modelBuilder.Entity("favoriser", b =>
                {
                    b.Property<int>("idutilisateur")
                        .HasColumnType("integer");

                    b.Property<int>("idannonce")
                        .HasColumnType("integer");

                    b.HasKey("idutilisateur", "idannonce")
                        .HasName("pk_favoriser");

                    b.HasIndex("idannonce");

                    b.ToTable("favoriser", "public");
                });

            modelBuilder.Entity("proposer", b =>
                {
                    b.Property<int>("idcommodite")
                        .HasColumnType("integer");

                    b.Property<int>("idannonce")
                        .HasColumnType("integer");

                    b.HasKey("idcommodite", "idannonce")
                        .HasName("pk_proposer");

                    b.HasIndex("idannonce");

                    b.ToTable("proposer", "public");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Ville", "VilleAdresse")
                        .WithMany("Adresses")
                        .HasForeignKey("VilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VilleAdresse");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Adresse", "AdresseAnnonce")
                        .WithMany()
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.DateReference", "DatePublication")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Heure", "HeureArrivee")
                        .WithMany()
                        .HasForeignKey("HeureArriveeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Heure", "HeureDepart")
                        .WithMany()
                        .HasForeignKey("HeureDepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.TypeHebergement", "TypeHebergementAssocie")
                        .WithMany("Annonces")
                        .HasForeignKey("TypeHebergementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "UtilisateurAuteur")
                        .WithMany("AnnoncesPubliees")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseAnnonce");

                    b.Navigation("DatePublication");

                    b.Navigation("HeureArrivee");

                    b.Navigation("HeureDepart");

                    b.Navigation("TypeHebergementAssocie");

                    b.Navigation("UtilisateurAuteur");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "AnnonceEvaluee")
                        .WithMany("Avis")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "AuteurAvis")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceEvaluee");

                    b.Navigation("AuteurAvis");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Commodite", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Categorie", "CategorieCommodite")
                        .WithMany("Commodites")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieCommodite");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Region", "RegionAssociee")
                        .WithMany("Departements")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegionAssociee");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Incident", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.DateReference", "DateIncident")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Reservation", "ReservationConcernee")
                        .WithMany("Incidents")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "UtilisateurDeclarant")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DateIncident");

                    b.Navigation("ReservationConcernee");

                    b.Navigation("UtilisateurDeclarant");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Message", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "Expediteur")
                        .WithMany()
                        .HasForeignKey("UtilisateurExpediteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "Receveur")
                        .WithMany()
                        .HasForeignKey("UtilisateurReceveurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediteur");

                    b.Navigation("Receveur");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Particulier", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "UtilisateurBase")
                        .WithOne("ProfilParticulier")
                        .HasForeignKey("LeboncoinAPI.Models.EntityFramework.Particulier", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtilisateurBase");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Professionnel", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "UtilisateurBase")
                        .WithOne("ProfilProfessionnel")
                        .HasForeignKey("LeboncoinAPI.Models.EntityFramework.Professionnel", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UtilisateurBase");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "AnnonceConcernee")
                        .WithMany("Reservations")
                        .HasForeignKey("AnnonceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnnonceConcernee");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.TypeHebergement", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Categorie", "CategorieHebergement")
                        .WithMany("TypesHebergements")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategorieHebergement");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Adresse", "AdresseUtilisateur")
                        .WithMany()
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.DateReference", "DateInscription")
                        .WithMany()
                        .HasForeignKey("DateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdresseUtilisateur");

                    b.Navigation("DateInscription");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Departement", "DepartementAssocie")
                        .WithMany("Villes")
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartementAssocie");
                });

            modelBuilder.Entity("demander", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Compensation", null)
                        .WithMany()
                        .HasForeignKey("idcompensation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_demander_compensation");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Incident", null)
                        .WithMany()
                        .HasForeignKey("idincident")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_demander_incident");
                });

            modelBuilder.Entity("favoriser", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("idannonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorise_favoriser_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("idutilisateur")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorise_favoriser_utilisateur");
                });

            modelBuilder.Entity("proposer", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("idannonce")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposer_proposer2_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Commodite", null)
                        .WithMany()
                        .HasForeignKey("idcommodite")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_proposer_proposer_commodit");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Categorie", b =>
                {
                    b.Navigation("Commodites");

                    b.Navigation("TypesHebergements");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.Navigation("Villes");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Region", b =>
                {
                    b.Navigation("Departements");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.TypeHebergement", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("AnnoncesPubliees");

                    b.Navigation("ProfilParticulier");

                    b.Navigation("ProfilProfessionnel");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.Navigation("Adresses");
                });
#pragma warning restore 612, 618
        }
    }
}
