// <auto-generated />
using System;
using LeboncoinAPI.Models.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeboncoinAPI.Migrations
{
    [DbContext(typeof(LeboncoinDBContext))]
    partial class LeboncoinDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnnonceAnnonce", b =>
                {
                    b.Property<int>("IdannonceA")
                        .HasColumnType("integer");

                    b.Property<int>("IdannonceB")
                        .HasColumnType("integer");

                    b.HasKey("IdannonceA", "IdannonceB");

                    b.ToTable("AnnonceAnnonce");
                });

            modelBuilder.Entity("AnnonceCommodite", b =>
                {
                    b.Property<int>("Idannonce")
                        .HasColumnType("integer");

                    b.Property<int>("Idcommodite")
                        .HasColumnType("integer");

                    b.HasKey("Idannonce", "Idcommodite");

                    b.ToTable("AnnonceCommodite");
                });

            modelBuilder.Entity("AnnonceUtilisateur", b =>
                {
                    b.Property<int>("Idannonce")
                        .HasColumnType("integer");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer");

                    b.HasKey("Idannonce", "Idutilisateur");

                    b.ToTable("AnnonceUtilisateur");
                });

            modelBuilder.Entity("Attribuer", b =>
                {
                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<int>("Idrole")
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    b.HasKey("Idutilisateur", "Idrole")
                        .HasName("pk_attribuer");

                    b.HasIndex("Idrole");

                    b.ToTable("attribuer", (string)null);
                });

            modelBuilder.Entity("Cibler", b =>
                {
                    b.Property<int>("Idtypehebergement")
                        .HasColumnType("integer")
                        .HasColumnName("idtypehebergement");

                    b.Property<int>("Idrecherche")
                        .HasColumnType("integer")
                        .HasColumnName("idrecherche");

                    b.HasKey("Idtypehebergement", "Idrecherche")
                        .HasName("pk_cibler");

                    b.HasIndex(new[] { "Idrecherche" }, "idx_cibler_idrecherche");

                    b.ToTable("cibler", (string)null);
                });

            modelBuilder.Entity("CommoditeRecherche", b =>
                {
                    b.Property<int>("Idcommodite")
                        .HasColumnType("integer");

                    b.Property<int>("Idrecherche")
                        .HasColumnType("integer");

                    b.HasKey("Idcommodite", "Idrecherche");

                    b.ToTable("CommoditeRecherche");
                });

            modelBuilder.Entity("CompensationIncident", b =>
                {
                    b.Property<int>("Idcompensation")
                        .HasColumnType("integer");

                    b.Property<int>("Idincident")
                        .HasColumnType("integer");

                    b.HasKey("Idcompensation", "Idincident");

                    b.ToTable("CompensationIncident");
                });

            modelBuilder.Entity("Demander", b =>
                {
                    b.Property<int>("Idincident")
                        .HasColumnType("integer")
                        .HasColumnName("idincident");

                    b.Property<int>("Idcompensation")
                        .HasColumnType("integer")
                        .HasColumnName("idcompensation");

                    b.HasKey("Idincident", "Idcompensation")
                        .HasName("pk_demander");

                    b.HasIndex(new[] { "Idcompensation" }, "idx_demander_idcompensation");

                    b.ToTable("demander", (string)null);
                });

            modelBuilder.Entity("Favoriser", b =>
                {
                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<int>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.HasKey("Idutilisateur", "Idannonce")
                        .HasName("pk_favoriser");

                    b.HasIndex(new[] { "Idannonce" }, "idx_favoriser_idannonce");

                    b.ToTable("favoriser", (string)null);
                });

            modelBuilder.Entity("Filtrer", b =>
                {
                    b.Property<int>("Idrecherche")
                        .HasColumnType("integer")
                        .HasColumnName("idrecherche");

                    b.Property<int>("Idcommodite")
                        .HasColumnType("integer")
                        .HasColumnName("idcommodite");

                    b.HasKey("Idrecherche", "Idcommodite")
                        .HasName("pk_filtrer");

                    b.HasIndex(new[] { "Idcommodite" }, "idx_filtrer_idcommodite");

                    b.ToTable("filtrer", (string)null);
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("Idadresse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idadresse"));

                    b.Property<int>("Idville")
                        .HasColumnType("integer")
                        .HasColumnName("idville");

                    b.Property<string>("Nomrue")
                        .HasMaxLength(39)
                        .HasColumnType("character varying(39)")
                        .HasColumnName("nomrue");

                    b.Property<int?>("Numerorue")
                        .HasColumnType("integer")
                        .HasColumnName("numerorue");

                    b.HasKey("Idadresse")
                        .HasName("pk_adresse");

                    b.HasIndex(new[] { "Idville" }, "idx_adresse_idville");

                    b.ToTable("adresse");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.Property<int>("Idannonce")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idannonce"));

                    b.Property<int?>("Capacite")
                        .HasColumnType("integer")
                        .HasColumnName("capacite");

                    b.Property<string>("Descriptionannonce")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descriptionannonce");

                    b.Property<bool>("Estverifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estverifie");

                    b.Property<int>("Idadresse")
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("Idheurearrivee")
                        .HasColumnType("integer")
                        .HasColumnName("idheurearrivee");

                    b.Property<int>("Idheuredepart")
                        .HasColumnType("integer")
                        .HasColumnName("idheuredepart");

                    b.Property<int>("Idtypehebergement")
                        .HasColumnType("integer")
                        .HasColumnName("idtypehebergement");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<int?>("Minimumnuitee")
                        .HasColumnType("integer")
                        .HasColumnName("minimumnuitee");

                    b.Property<decimal?>("Montantacompte")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montantacompte");

                    b.Property<int?>("Nbchambres")
                        .HasColumnType("integer")
                        .HasColumnName("nbchambres");

                    b.Property<int?>("Nombrebebesmax")
                        .HasColumnType("integer")
                        .HasColumnName("nombrebebesmax");

                    b.Property<int?>("Nombreetoilesleboncoin")
                        .HasColumnType("integer")
                        .HasColumnName("nombreetoilesleboncoin");

                    b.Property<bool>("Possibiliteanimaux")
                        .HasColumnType("boolean")
                        .HasColumnName("possibiliteanimaux");

                    b.Property<bool>("Possibilitefumeur")
                        .HasColumnType("boolean")
                        .HasColumnName("possibilitefumeur");

                    b.Property<int?>("Pourcentageacompte")
                        .HasColumnType("integer")
                        .HasColumnName("pourcentageacompte");

                    b.Property<decimal>("Prixnuitee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prixnuitee");

                    b.Property<bool>("Smsverifie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("smsverifie");

                    b.Property<string>("Titreannonce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("titreannonce");

                    b.HasKey("Idannonce")
                        .HasName("pk_annonce");

                    b.HasIndex(new[] { "Capacite" }, "idx_annonce_capacite");

                    b.HasIndex(new[] { "Idadresse" }, "idx_annonce_idadresse");

                    b.HasIndex(new[] { "Iddate" }, "idx_annonce_iddate");

                    b.HasIndex(new[] { "Idheurearrivee" }, "idx_annonce_idheurearrivee");

                    b.HasIndex(new[] { "Idheuredepart" }, "idx_annonce_idheuredepart");

                    b.HasIndex(new[] { "Idtypehebergement" }, "idx_annonce_idtypehebergement");

                    b.HasIndex(new[] { "Idutilisateur" }, "idx_annonce_idutilisateur");

                    b.HasIndex(new[] { "Nbchambres" }, "idx_annonce_nbchambres");

                    b.HasIndex(new[] { "Prixnuitee" }, "idx_annonce_prixnuitee");

                    b.ToTable("annonce");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Avi", b =>
                {
                    b.Property<int>("Idavis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idavis");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idavis"));

                    b.Property<int>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<decimal>("Nombreetoiles")
                        .HasPrecision(2, 1)
                        .HasColumnType("numeric(2,1)")
                        .HasColumnName("nombreetoiles");

                    b.Property<string>("Texteavis")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("texteavis");

                    b.HasKey("Idavis")
                        .HasName("pk_avis");

                    b.HasIndex("Idannonce");

                    b.HasIndex("Iddate");

                    b.HasIndex("Idutilisateur");

                    b.ToTable("avis");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.Property<int>("Idcartebancaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcartebancaire");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcartebancaire"));

                    b.Property<DateOnly?>("Dateexpiration")
                        .HasColumnType("date")
                        .HasColumnName("dateexpiration");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Nomtitulaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomtitulaire");

                    b.Property<decimal?>("Numerocartebancaire")
                        .HasPrecision(16)
                        .HasColumnType("numeric(16,0)")
                        .HasColumnName("numerocartebancaire");

                    b.Property<decimal?>("Numerocvv")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)")
                        .HasColumnName("numerocvv");

                    b.Property<string>("Prenomtitulaire")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomtitulaire");

                    b.HasKey("Idcartebancaire")
                        .HasName("pk_cartebancaire");

                    b.HasIndex("Idutilisateur");

                    b.ToTable("cartebancaire");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Categorie", b =>
                {
                    b.Property<int>("Idcategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcategorie"));

                    b.Property<string>("Nomcategorie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomcategorie");

                    b.HasKey("Idcategorie")
                        .HasName("pk_categorie");

                    b.ToTable("categorie");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Commodite", b =>
                {
                    b.Property<int>("Idcommodite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcommodite");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcommodite"));

                    b.Property<int>("Idcategorie")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    b.Property<string>("Nomcommodite")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomcommodite");

                    b.HasKey("Idcommodite")
                        .HasName("pk_commodite");

                    b.HasIndex(new[] { "Idcategorie" }, "idx_commodite_idcategorie");

                    b.ToTable("commodite");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Compensation", b =>
                {
                    b.Property<int>("Idcompensation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idcompensation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idcompensation"));

                    b.Property<string>("Nomcompensation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomcompensation");

                    b.HasKey("Idcompensation")
                        .HasName("pk_compensation");

                    b.ToTable("compensation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Date", b =>
                {
                    b.Property<int>("Iddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Iddate"));

                    b.Property<DateOnly?>("Date1")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.HasKey("Iddate")
                        .HasName("pk_date");

                    b.HasIndex(new[] { "Date1" }, "idx_date_date");

                    b.ToTable("date");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.Property<int>("Iddepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("iddepartement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Iddepartement"));

                    b.Property<int>("Idregion")
                        .HasColumnType("integer")
                        .HasColumnName("idregion");

                    b.Property<string>("Nomdepartement")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("nomdepartement");

                    b.Property<string>("Numerodepartement")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("numerodepartement");

                    b.HasKey("Iddepartement")
                        .HasName("pk_departement");

                    b.HasIndex(new[] { "Idregion" }, "idx_departement_idregion");

                    b.ToTable("departement");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Heure", b =>
                {
                    b.Property<int>("Idheure")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idheure");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idheure"));

                    b.Property<TimeOnly>("Heure1")
                        .HasColumnType("time without time zone")
                        .HasColumnName("heure");

                    b.HasKey("Idheure")
                        .HasName("pk_heure");

                    b.ToTable("heure");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Incident", b =>
                {
                    b.Property<int>("Idincident")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idincident");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idincident"));

                    b.Property<string>("Descriptionincident")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("descriptionincident");

                    b.Property<bool>("Estclasse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estclasse");

                    b.Property<bool>("Estrembourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estrembourse");

                    b.Property<bool>("Estremisaucontentieux")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estremisaucontentieux");

                    b.Property<int>("Etape")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("etape");

                    b.Property<string>("Explicationproprietaire")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("explicationproprietaire");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("Idreservation")
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Motifincident")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("motifincident");

                    b.HasKey("Idincident")
                        .HasName("pk_incident");

                    b.HasIndex("Iddate");

                    b.HasIndex(new[] { "Idreservation" }, "idx_incident_idreservation");

                    b.HasIndex(new[] { "Idutilisateur" }, "idx_incident_idutilisateur");

                    b.ToTable("incident");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Inclure", b =>
                {
                    b.Property<int>("Idreservation")
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    b.Property<int>("Idtypevoyageur")
                        .HasColumnType("integer")
                        .HasColumnName("idtypevoyageur");

                    b.Property<int>("Nombrevoyageur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("nombrevoyageur");

                    b.HasKey("Idreservation", "Idtypevoyageur")
                        .HasName("pk_inclure");

                    b.HasIndex(new[] { "Idtypevoyageur" }, "idx_inclure_idtypevoyageur");

                    b.ToTable("inclure");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Message", b =>
                {
                    b.Property<int>("Idmessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idmessage");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idmessage"));

                    b.Property<string>("Contenumessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("contenumessage");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("Idutilisateurexpediteur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateurexpediteur");

                    b.Property<int>("Idutilisateurreceveur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateurreceveur");

                    b.HasKey("Idmessage")
                        .HasName("pk_message");

                    b.HasIndex("Iddate");

                    b.HasIndex(new[] { "Idutilisateurexpediteur" }, "idx_message_idutilisateurexpediteur");

                    b.HasIndex(new[] { "Idutilisateurreceveur" }, "idx_message_idutilisateurreceveur");

                    b.ToTable("message");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Particulier", b =>
                {
                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Civilite")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("civilite");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<string>("Nomutilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomutilisateur");

                    b.Property<string>("Prenomutilisateur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomutilisateur");

                    b.HasKey("Idutilisateur")
                        .HasName("pk_particulier");

                    b.HasIndex("Iddate");

                    b.ToTable("particulier");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Permission", b =>
                {
                    b.Property<int>("Idpermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idpermission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idpermission"));

                    b.Property<string>("Nompermission")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nompermission");

                    b.HasKey("Idpermission")
                        .HasName("pk_permission");

                    b.ToTable("permission");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Photo", b =>
                {
                    b.Property<int>("Idphoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idphoto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idphoto"));

                    b.Property<int?>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int?>("Idincident")
                        .HasColumnType("integer")
                        .HasColumnName("idincident");

                    b.Property<string>("Lienphoto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lienphoto");

                    b.HasKey("Idphoto")
                        .HasName("pk_photo");

                    b.HasIndex("Idannonce");

                    b.HasIndex("Idincident");

                    b.ToTable("photo");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Professionnel", b =>
                {
                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Nomsociete")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomsociete");

                    b.Property<decimal>("Numsiret")
                        .HasPrecision(14)
                        .HasColumnType("numeric(14,0)")
                        .HasColumnName("numsiret");

                    b.Property<string>("Secteuractivite")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("secteuractivite");

                    b.HasKey("Idutilisateur")
                        .HasName("pk_professionnel");

                    b.HasIndex(new[] { "Numsiret" }, "professionnel_numsiret_key")
                        .IsUnique();

                    b.ToTable("professionnel");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Recherche", b =>
                {
                    b.Property<int>("Idrecherche")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idrecherche");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idrecherche"));

                    b.Property<int?>("Capaciteminimumvoyageur")
                        .HasColumnType("integer")
                        .HasColumnName("capaciteminimumvoyageur");

                    b.Property<int?>("Iddatedebutrecherche")
                        .HasColumnType("integer")
                        .HasColumnName("iddatedebutrecherche");

                    b.Property<int?>("Iddatefinrecherche")
                        .HasColumnType("integer")
                        .HasColumnName("iddatefinrecherche");

                    b.Property<int?>("Iddepartement")
                        .HasColumnType("integer")
                        .HasColumnName("iddepartement");

                    b.Property<int?>("Idregion")
                        .HasColumnType("integer")
                        .HasColumnName("idregion");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<int?>("Idville")
                        .HasColumnType("integer")
                        .HasColumnName("idville");

                    b.Property<int?>("Nombremaximumchambre")
                        .HasColumnType("integer")
                        .HasColumnName("nombremaximumchambre");

                    b.Property<int?>("Nombreminimumchambre")
                        .HasColumnType("integer")
                        .HasColumnName("nombreminimumchambre");

                    b.Property<bool>("Paiementenligne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("paiementenligne");

                    b.Property<decimal?>("Prixmaximum")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prixmaximum");

                    b.Property<decimal?>("Prixminimum")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prixminimum");

                    b.HasKey("Idrecherche")
                        .HasName("pk_recherche");

                    b.HasIndex("Iddatedebutrecherche");

                    b.HasIndex("Iddatefinrecherche");

                    b.HasIndex("Iddepartement");

                    b.HasIndex("Idregion");

                    b.HasIndex("Idutilisateur");

                    b.HasIndex("Idville");

                    b.ToTable("recherche");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Region", b =>
                {
                    b.Property<int>("Idregion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idregion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idregion"));

                    b.Property<string>("Nomregion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomregion");

                    b.HasKey("Idregion")
                        .HasName("pk_region");

                    b.HasIndex(new[] { "Nomregion" }, "region_nomregion_key")
                        .IsUnique();

                    b.ToTable("region");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Relier", b =>
                {
                    b.Property<int>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<bool>("Estdisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("estdisponible");

                    b.HasKey("Idannonce", "Iddate")
                        .HasName("pk_relier");

                    b.HasIndex(new[] { "Iddate" }, "idx_relier_iddate");

                    b.ToTable("relier");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Property<int>("Idreservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idreservation"));

                    b.Property<int>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.Property<int>("Iddatedebutreservation")
                        .HasColumnType("integer")
                        .HasColumnName("iddatedebutreservation");

                    b.Property<int>("Iddatefinreservation")
                        .HasColumnType("integer")
                        .HasColumnName("iddatefinreservation");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    b.Property<string>("Nomclient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nomclient");

                    b.Property<string>("Prenomclient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prenomclient");

                    b.Property<string>("Telephoneclient")
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telephoneclient")
                        .IsFixedLength();

                    b.HasKey("Idreservation")
                        .HasName("pk_reservation");

                    b.HasIndex(new[] { "Idannonce" }, "idx_reservation_idannonce");

                    b.HasIndex(new[] { "Iddatedebutreservation" }, "idx_reservation_iddatedebutres");

                    b.HasIndex(new[] { "Iddatefinreservation" }, "idx_reservation_iddatefinres");

                    b.HasIndex(new[] { "Idutilisateur" }, "idx_reservation_idutilisateur");

                    b.ToTable("reservation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Role", b =>
                {
                    b.Property<int>("Idrole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idrole"));

                    b.Property<string>("Nomrole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomrole");

                    b.HasKey("Idrole")
                        .HasName("pk_role");

                    b.ToTable("role");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Transaction", b =>
                {
                    b.Property<int>("Idtransaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtransaction");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtransaction"));

                    b.Property<int>("Idcartebancaire")
                        .HasColumnType("integer")
                        .HasColumnName("idcartebancaire");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<int>("Idreservation")
                        .HasColumnType("integer")
                        .HasColumnName("idreservation");

                    b.Property<decimal>("Montanttransaction")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("montanttransaction");

                    b.HasKey("Idtransaction")
                        .HasName("pk_transaction");

                    b.HasIndex(new[] { "Idcartebancaire" }, "idx_transaction_idcartebancaire");

                    b.HasIndex(new[] { "Iddate" }, "idx_transaction_iddate");

                    b.HasIndex(new[] { "Idreservation" }, "idx_transaction_idreservation");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Typehebergement", b =>
                {
                    b.Property<int>("Idtypehebergement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypehebergement");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtypehebergement"));

                    b.Property<int>("Idcategorie")
                        .HasColumnType("integer")
                        .HasColumnName("idcategorie");

                    b.Property<string>("Nomtypehebergement")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomtypehebergement");

                    b.HasKey("Idtypehebergement")
                        .HasName("pk_typehebergement");

                    b.HasIndex(new[] { "Idcategorie" }, "idx_typehebergement_idcategorie");

                    b.ToTable("typehebergement");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Typevoyageur", b =>
                {
                    b.Property<int>("Idtypevoyageur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idtypevoyageur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idtypevoyageur"));

                    b.Property<string>("Nomtypevoyageur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("nomtypevoyageur");

                    b.HasKey("Idtypevoyageur")
                        .HasName("pk_typevoyageur");

                    b.HasIndex(new[] { "Nomtypevoyageur" }, "typevoyageur_nomtypevoyageur_key")
                        .IsUnique();

                    b.ToTable("typevoyageur");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Property<int>("Idutilisateur")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idutilisateur");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idutilisateur"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("Idadresse")
                        .HasColumnType("integer")
                        .HasColumnName("idadresse");

                    b.Property<int?>("Idcartebancaire")
                        .HasColumnType("integer")
                        .HasColumnName("idcartebancaire");

                    b.Property<int>("Iddate")
                        .HasColumnType("integer")
                        .HasColumnName("iddate");

                    b.Property<bool>("IdentityVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("identity_verified");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<bool>("PhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_verified");

                    b.Property<string>("ProfilePhotoPath")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("profile_photo_path");

                    b.Property<string>("Pseudonyme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pseudonyme");

                    b.Property<string>("RememberToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("remember_token");

                    b.Property<decimal>("Solde")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("solde");

                    b.Property<string>("Telephoneutilisateur")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character(10)")
                        .HasColumnName("telephoneutilisateur")
                        .IsFixedLength();

                    b.Property<DateTime?>("TwoFactorConfirmedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("two_factor_confirmed_at");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_recovery_codes");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("text")
                        .HasColumnName("two_factor_secret");

                    b.HasKey("Idutilisateur")
                        .HasName("pk_utilisateur");

                    b.HasIndex(new[] { "Idadresse" }, "idx_utilisateur_idadresse");

                    b.HasIndex(new[] { "Idcartebancaire" }, "idx_utilisateur_idcartebancaire");

                    b.HasIndex(new[] { "Iddate" }, "idx_utilisateur_iddate");

                    b.HasIndex(new[] { "Email" }, "utilisateur_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Telephoneutilisateur" }, "utilisateur_telephoneutilisateur_key")
                        .IsUnique();

                    b.ToTable("utilisateur");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.Property<int>("Idville")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("idville");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Idville"));

                    b.Property<string>("Codepostal")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .HasColumnName("codepostal")
                        .IsFixedLength();

                    b.Property<int>("Iddepartement")
                        .HasColumnType("integer")
                        .HasColumnName("iddepartement");

                    b.Property<string>("Nomville")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nomville");

                    b.Property<decimal>("Taxedesejour")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("taxedesejour");

                    b.HasKey("Idville")
                        .HasName("pk_ville");

                    b.HasIndex(new[] { "Iddepartement" }, "idx_ville_iddepartement");

                    b.ToTable("ville");
                });

            modelBuilder.Entity("Permettre", b =>
                {
                    b.Property<int>("Idrole")
                        .HasColumnType("integer")
                        .HasColumnName("idrole");

                    b.Property<int>("Idpermission")
                        .HasColumnType("integer")
                        .HasColumnName("idpermission");

                    b.HasKey("Idrole", "Idpermission")
                        .HasName("pk_permettre");

                    b.HasIndex("Idpermission");

                    b.ToTable("permettre", (string)null);
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<int>("Idpermission")
                        .HasColumnType("integer");

                    b.Property<int>("Idrole")
                        .HasColumnType("integer");

                    b.HasKey("Idpermission", "Idrole");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Proposer", b =>
                {
                    b.Property<int>("Idcommodite")
                        .HasColumnType("integer")
                        .HasColumnName("idcommodite");

                    b.Property<int>("Idannonce")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce");

                    b.HasKey("Idcommodite", "Idannonce")
                        .HasName("pk_proposer");

                    b.HasIndex(new[] { "Idannonce" }, "idx_proposer_idannonce");

                    b.HasIndex(new[] { "Idcommodite" }, "idx_proposer_idcommodite");

                    b.ToTable("proposer", (string)null);
                });

            modelBuilder.Entity("RechercheTypehebergement", b =>
                {
                    b.Property<int>("Idrecherche")
                        .HasColumnType("integer");

                    b.Property<int>("Idtypehebergement")
                        .HasColumnType("integer");

                    b.HasKey("Idrecherche", "Idtypehebergement");

                    b.ToTable("RechercheTypehebergement");
                });

            modelBuilder.Entity("Ressembler", b =>
                {
                    b.Property<int>("IdannonceA")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce_a");

                    b.Property<int>("IdannonceB")
                        .HasColumnType("integer")
                        .HasColumnName("idannonce_b");

                    b.HasKey("IdannonceA", "IdannonceB")
                        .HasName("pk_ressembler");

                    b.HasIndex(new[] { "IdannonceB" }, "idx_ressembler_idannonce_b");

                    b.ToTable("ressembler", (string)null);
                });

            modelBuilder.Entity("RoleUtilisateur", b =>
                {
                    b.Property<int>("Idrole")
                        .HasColumnType("integer");

                    b.Property<int>("Idutilisateur")
                        .HasColumnType("integer");

                    b.HasKey("Idrole", "Idutilisateur");

                    b.ToTable("RoleUtilisateur");
                });

            modelBuilder.Entity("Attribuer", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Role", null)
                        .WithMany()
                        .HasForeignKey("Idrole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribuer_role");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attribuer_utilisateur");
                });

            modelBuilder.Entity("Cibler", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Recherche", null)
                        .WithMany()
                        .HasForeignKey("Idrecherche")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cibler_cibler2_recherch");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Typehebergement", null)
                        .WithMany()
                        .HasForeignKey("Idtypehebergement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cibler_cibler_typehebe");
                });

            modelBuilder.Entity("Demander", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Compensation", null)
                        .WithMany()
                        .HasForeignKey("Idcompensation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_demander_compensation");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Incident", null)
                        .WithMany()
                        .HasForeignKey("Idincident")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_demander_incident");
                });

            modelBuilder.Entity("Favoriser", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorise_favoriser_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", null)
                        .WithMany()
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_favorise_favoriser_utilisateur");
                });

            modelBuilder.Entity("Filtrer", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Commodite", null)
                        .WithMany()
                        .HasForeignKey("Idcommodite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_filtrer_filtrer2_commodit");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Recherche", null)
                        .WithMany()
                        .HasForeignKey("Idrecherche")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_filtrer_filtrer_recherch");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Ville", "IdvilleNavigation")
                        .WithMany("Adresses")
                        .HasForeignKey("Idville")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_adresse_posseder_ville");

                    b.Navigation("IdvilleNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Adresse", "IdadresseNavigation")
                        .WithMany("Annonces")
                        .HasForeignKey("Idadresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_se_trouve_adresse");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Annonces")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_publier_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Heure", "IdheurearriveeNavigation")
                        .WithMany("AnnonceIdheurearriveeNavigations")
                        .HasForeignKey("Idheurearrivee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_arriver_heure");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Heure", "IdheuredepartNavigation")
                        .WithMany("AnnonceIdheuredepartNavigations")
                        .HasForeignKey("Idheuredepart")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_partir_heure");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Typehebergement", "IdtypehebergementNavigation")
                        .WithMany("Annonces")
                        .HasForeignKey("Idtypehebergement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_qualifier_typehebe");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Annonces")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_annonce_diffuser_utilisateur");

                    b.Navigation("IdadresseNavigation");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdheurearriveeNavigation");

                    b.Navigation("IdheuredepartNavigation");

                    b.Navigation("IdtypehebergementNavigation");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Avi", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "IdannonceNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avis_noter_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avis_deposer_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Avis")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avis_commenter_utilisateur");

                    b.Navigation("IdannonceNavigation");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Cartebancaires")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_carteban_enregistr_utilisat");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Commodite", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Categorie", "IdcategorieNavigation")
                        .WithMany("Commodites")
                        .HasForeignKey("Idcategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_commodit_apparteni_categori");

                    b.Navigation("IdcategorieNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Region", "IdregionNavigation")
                        .WithMany("Departements")
                        .HasForeignKey("Idregion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_departem_localiser_region");

                    b.Navigation("IdregionNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Incident", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Incidents")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_associati_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Reservation", "IdreservationNavigation")
                        .WithMany("Incidents")
                        .HasForeignKey("Idreservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_associati_reservat");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Incidents")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_associati_utilisat");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdreservationNavigation");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Inclure", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Reservation", "IdreservationNavigation")
                        .WithMany("Inclures")
                        .HasForeignKey("Idreservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inclure_inclure_reservat");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Typevoyageur", "IdtypevoyageurNavigation")
                        .WithMany("Inclures")
                        .HasForeignKey("Idtypevoyageur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inclure_inclure2_typevoya");

                    b.Navigation("IdreservationNavigation");

                    b.Navigation("IdtypevoyageurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Message", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_associati_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurexpediteurNavigation")
                        .WithMany("MessageIdutilisateurexpediteurNavigations")
                        .HasForeignKey("Idutilisateurexpediteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_expedier_utilisat");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurreceveurNavigation")
                        .WithMany("MessageIdutilisateurreceveurNavigations")
                        .HasForeignKey("Idutilisateurreceveur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_message_recevoir_utilisat");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdutilisateurexpediteurNavigation");

                    b.Navigation("IdutilisateurreceveurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Particulier", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Particuliers")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_particulier_naitre_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithOne("Particulier")
                        .HasForeignKey("LeboncoinAPI.Models.EntityFramework.Particulier", "Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_particulier_heritage__utilisateur");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Photo", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "IdannonceNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_photo_comporter_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Incident", "IdincidentNavigation")
                        .WithMany("Photos")
                        .HasForeignKey("Idincident")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_photo_prouver_incident");

                    b.Navigation("IdannonceNavigation");

                    b.Navigation("IdincidentNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Professionnel", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithOne("Professionnel")
                        .HasForeignKey("LeboncoinAPI.Models.EntityFramework.Professionnel", "Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_professionnel_heritage__utilisateur");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Recherche", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddatedebutrechercheNavigation")
                        .WithMany("RechercheIddatedebutrechercheNavigations")
                        .HasForeignKey("Iddatedebutrecherche")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recherch_commencer_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddatefinrechercheNavigation")
                        .WithMany("RechercheIddatefinrechercheNavigations")
                        .HasForeignKey("Iddatefinrecherche")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recherch_terminer_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Departement", "IddepartementNavigation")
                        .WithMany("Recherches")
                        .HasForeignKey("Iddepartement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recherch_connecter_departem");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Region", "IdregionNavigation")
                        .WithMany("Recherches")
                        .HasForeignKey("Idregion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recherch_lier_region");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Recherches")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recherch_associati_utilisat");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Ville", "IdvilleNavigation")
                        .WithMany("Recherches")
                        .HasForeignKey("Idville")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recherch_associer_ville");

                    b.Navigation("IddatedebutrechercheNavigation");

                    b.Navigation("IddatefinrechercheNavigation");

                    b.Navigation("IddepartementNavigation");

                    b.Navigation("IdregionNavigation");

                    b.Navigation("IdutilisateurNavigation");

                    b.Navigation("IdvilleNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Relier", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "IdannonceNavigation")
                        .WithMany("Reliers")
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relier_relier_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Reliers")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relier_relier2_date");

                    b.Navigation("IdannonceNavigation");

                    b.Navigation("IddateNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", "IdannonceNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservat_concerner_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddatedebutreservationNavigation")
                        .WithMany("ReservationIddatedebutreservationNavigations")
                        .HasForeignKey("Iddatedebutreservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservat_debuter_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddatefinreservationNavigation")
                        .WithMany("ReservationIddatefinreservationNavigations")
                        .HasForeignKey("Iddatefinreservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservat_finir_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Utilisateur", "IdutilisateurNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("Idutilisateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_reserver_utilisateur");

                    b.Navigation("IdannonceNavigation");

                    b.Navigation("IddatedebutreservationNavigation");

                    b.Navigation("IddatefinreservationNavigation");

                    b.Navigation("IdutilisateurNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Transaction", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Cartebancaire", "IdcartebancaireNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("Idcartebancaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transact_faire_carteban");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transact_effectuer_date");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Reservation", "IdreservationNavigation")
                        .WithMany("Transactions")
                        .HasForeignKey("Idreservation")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transact_regler_reservat");

                    b.Navigation("IdcartebancaireNavigation");

                    b.Navigation("IddateNavigation");

                    b.Navigation("IdreservationNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Typehebergement", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Categorie", "IdcategorieNavigation")
                        .WithMany("Typehebergements")
                        .HasForeignKey("Idcategorie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_typehebe_classer_categori");

                    b.Navigation("IdcategorieNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Adresse", "IdadresseNavigation")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("Idadresse")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_utilisat_resider_adresse");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Cartebancaire", "IdcartebancaireNavigation")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("Idcartebancaire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_utilisat_enregistr_carteban");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Date", "IddateNavigation")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("Iddate")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_utilisat_creer_date");

                    b.Navigation("IdadresseNavigation");

                    b.Navigation("IdcartebancaireNavigation");

                    b.Navigation("IddateNavigation");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Departement", "IddepartementNavigation")
                        .WithMany("Villes")
                        .HasForeignKey("Iddepartement")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ville_situer_departem");

                    b.Navigation("IddepartementNavigation");
                });

            modelBuilder.Entity("Permettre", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Permission", null)
                        .WithMany()
                        .HasForeignKey("Idpermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permettre_permission");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Role", null)
                        .WithMany()
                        .HasForeignKey("Idrole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permettre_role");
                });

            modelBuilder.Entity("Proposer", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("Idannonce")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proposer_proposer2_annonce");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Commodite", null)
                        .WithMany()
                        .HasForeignKey("Idcommodite")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_proposer_proposer_commodit");
                });

            modelBuilder.Entity("Ressembler", b =>
                {
                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("IdannonceA")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ressembler_idannonce_a");

                    b.HasOne("LeboncoinAPI.Models.EntityFramework.Annonce", null)
                        .WithMany()
                        .HasForeignKey("IdannonceB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ressembler_idannonce_b");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Annonce", b =>
                {
                    b.Navigation("Avis");

                    b.Navigation("Photos");

                    b.Navigation("Reliers");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Cartebancaire", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Categorie", b =>
                {
                    b.Navigation("Commodites");

                    b.Navigation("Typehebergements");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Date", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Avis");

                    b.Navigation("Incidents");

                    b.Navigation("Messages");

                    b.Navigation("Particuliers");

                    b.Navigation("RechercheIddatedebutrechercheNavigations");

                    b.Navigation("RechercheIddatefinrechercheNavigations");

                    b.Navigation("Reliers");

                    b.Navigation("ReservationIddatedebutreservationNavigations");

                    b.Navigation("ReservationIddatefinreservationNavigations");

                    b.Navigation("Transactions");

                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Departement", b =>
                {
                    b.Navigation("Recherches");

                    b.Navigation("Villes");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Heure", b =>
                {
                    b.Navigation("AnnonceIdheurearriveeNavigations");

                    b.Navigation("AnnonceIdheuredepartNavigations");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Incident", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Region", b =>
                {
                    b.Navigation("Departements");

                    b.Navigation("Recherches");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Reservation", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Inclures");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Typehebergement", b =>
                {
                    b.Navigation("Annonces");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Typevoyageur", b =>
                {
                    b.Navigation("Inclures");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Utilisateur", b =>
                {
                    b.Navigation("Annonces");

                    b.Navigation("Avis");

                    b.Navigation("Cartebancaires");

                    b.Navigation("Incidents");

                    b.Navigation("MessageIdutilisateurexpediteurNavigations");

                    b.Navigation("MessageIdutilisateurreceveurNavigations");

                    b.Navigation("Particulier");

                    b.Navigation("Professionnel");

                    b.Navigation("Recherches");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("LeboncoinAPI.Models.EntityFramework.Ville", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Recherches");
                });
#pragma warning restore 612, 618
        }
    }
}
