CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE public.categorie (
    idcategorie integer GENERATED BY DEFAULT AS IDENTITY,
    nomcategorie character varying(24),
    CONSTRAINT "PK_categorie" PRIMARY KEY (idcategorie)
);

CREATE TABLE public.compensation (
    idcompensation integer GENERATED BY DEFAULT AS IDENTITY,
    nomcompensation character varying(100),
    CONSTRAINT "PK_compensation" PRIMARY KEY (idcompensation)
);

CREATE TABLE public.date (
    iddate integer GENERATED BY DEFAULT AS IDENTITY,
    date date,
    CONSTRAINT "PK_date" PRIMARY KEY (iddate)
);

CREATE TABLE public.heure (
    idheure integer GENERATED BY DEFAULT AS IDENTITY,
    heure time NOT NULL,
    CONSTRAINT "PK_heure" PRIMARY KEY (idheure)
);

CREATE TABLE public.region (
    idregion integer GENERATED BY DEFAULT AS IDENTITY,
    nomregion character varying(30) NOT NULL,
    CONSTRAINT "PK_region" PRIMARY KEY (idregion)
);

CREATE TABLE public.typevoyageur (
    idtypevoyageur integer GENERATED BY DEFAULT AS IDENTITY,
    nomtypevoyageur character varying(30) NOT NULL,
    CONSTRAINT "PK_typevoyageur" PRIMARY KEY (idtypevoyageur)
);

CREATE TABLE public.commodite (
    idcommodite integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomcommodite character varying(50),
    CONSTRAINT "PK_commodite" PRIMARY KEY (idcommodite),
    CONSTRAINT "FK_commodite_categorie_idcategorie" FOREIGN KEY (idcategorie) REFERENCES public.categorie (idcategorie) ON DELETE CASCADE
);

CREATE TABLE public.typehebergement (
    idtypehebergement integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomtypehebergement character varying(30),
    CONSTRAINT "PK_typehebergement" PRIMARY KEY (idtypehebergement),
    CONSTRAINT "FK_typehebergement_categorie_idcategorie" FOREIGN KEY (idcategorie) REFERENCES public.categorie (idcategorie) ON DELETE CASCADE
);

CREATE TABLE public.departement (
    iddepartement integer GENERATED BY DEFAULT AS IDENTITY,
    idregion integer NOT NULL,
    numerodepartement character varying(3),
    nomdepartement character varying(25),
    CONSTRAINT "PK_departement" PRIMARY KEY (iddepartement),
    CONSTRAINT "FK_departement_region_idregion" FOREIGN KEY (idregion) REFERENCES public.region (idregion) ON DELETE CASCADE
);

CREATE TABLE public.ville (
    idville integer GENERATED BY DEFAULT AS IDENTITY,
    iddepartement integer NOT NULL,
    codepostal char(5) NOT NULL,
    nomville character varying(40) NOT NULL,
    taxedesejour numeric(10,2) NOT NULL,
    CONSTRAINT "PK_ville" PRIMARY KEY (idville),
    CONSTRAINT "FK_ville_departement_iddepartement" FOREIGN KEY (iddepartement) REFERENCES public.departement (iddepartement) ON DELETE CASCADE
);

CREATE TABLE public.adresse (
    idadresse integer GENERATED BY DEFAULT AS IDENTITY,
    idville integer NOT NULL,
    numerorue integer,
    nomrue character varying(39),
    CONSTRAINT "PK_adresse" PRIMARY KEY (idadresse),
    CONSTRAINT "FK_adresse_ville_idville" FOREIGN KEY (idville) REFERENCES public.ville (idville) ON DELETE CASCADE
);

CREATE TABLE public.utilisateur (
    idutilisateur integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    iddate integer NOT NULL,
    pseudonyme character varying(50) NOT NULL,
    email character varying(320) NOT NULL,
    email_verified_at timestamp with time zone,
    password character varying(255) NOT NULL,
    telephoneutilisateur char(10) NOT NULL,
    phone_verified boolean NOT NULL DEFAULT FALSE,
    identity_verified boolean NOT NULL DEFAULT FALSE,
    solde numeric(10,2) NOT NULL DEFAULT 0.0,
    remember_token character varying(100),
    two_factor_secret text,
    two_factor_recovery_codes text,
    two_factor_confirmed_at timestamp with time zone,
    profile_photo_path character varying(2048),
    CONSTRAINT pk_utilisateur PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_utilisateur_adresse_idadresse" FOREIGN KEY (idadresse) REFERENCES public.adresse (idadresse) ON DELETE CASCADE,
    CONSTRAINT "FK_utilisateur_date_iddate" FOREIGN KEY (iddate) REFERENCES public.date (iddate) ON DELETE CASCADE
);

CREATE TABLE public.annonce (
    idannonce integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    iddate integer NOT NULL,
    idheuredepart integer NOT NULL,
    idtypehebergement integer NOT NULL,
    idheurearrivee integer NOT NULL,
    idutilisateur integer NOT NULL,
    titreannonce character varying(50) NOT NULL,
    descriptionannonce character varying(4000) NOT NULL,
    nombreetoilesleboncoin integer,
    lienphoto character varying(50) NOT NULL,
    montantacompte numeric(10,2),
    pourcentageacompte integer,
    prixnuitee numeric(10,2) NOT NULL,
    capacite integer,
    nbchambres integer,
    minimumnuitee integer,
    possibiliteanimaux boolean NOT NULL,
    nombrebebesmax integer,
    possibilitefumeur boolean NOT NULL,
    estverifie boolean NOT NULL DEFAULT FALSE,
    smsverifie boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_annonce PRIMARY KEY (idannonce),
    CONSTRAINT "FK_annonce_adresse_idadresse" FOREIGN KEY (idadresse) REFERENCES public.adresse (idadresse) ON DELETE CASCADE,
    CONSTRAINT "FK_annonce_date_iddate" FOREIGN KEY (iddate) REFERENCES public.date (iddate) ON DELETE CASCADE,
    CONSTRAINT "FK_annonce_heure_idheurearrivee" FOREIGN KEY (idheurearrivee) REFERENCES public.heure (idheure) ON DELETE CASCADE,
    CONSTRAINT "FK_annonce_heure_idheuredepart" FOREIGN KEY (idheuredepart) REFERENCES public.heure (idheure) ON DELETE CASCADE,
    CONSTRAINT "FK_annonce_typehebergement_idtypehebergement" FOREIGN KEY (idtypehebergement) REFERENCES public.typehebergement (idtypehebergement) ON DELETE CASCADE,
    CONSTRAINT "FK_annonce_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.message (
    idmessage integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateurreceveur integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateurexpediteur integer NOT NULL,
    contenumessage character varying(1000) NOT NULL,
    CONSTRAINT "PK_message" PRIMARY KEY (idmessage),
    CONSTRAINT "FK_message_utilisateur_idutilisateurexpediteur" FOREIGN KEY (idutilisateurexpediteur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE,
    CONSTRAINT "FK_message_utilisateur_idutilisateurreceveur" FOREIGN KEY (idutilisateurreceveur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.particulier (
    idutilisateur integer NOT NULL,
    nomutilisateur character varying(50) NOT NULL,
    prenomutilisateur character varying(50) NOT NULL,
    civilite character varying(15) NOT NULL,
    iddate integer NOT NULL,
    CONSTRAINT "PK_particulier" PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_particulier_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.professionnel (
    idutilisateur integer NOT NULL,
    numsiret numeric(14,0) NOT NULL,
    nomsociete character varying(30) NOT NULL,
    secteuractivite character varying(50) NOT NULL,
    CONSTRAINT "PK_professionnel" PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_professionnel_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.avis (
    idavis integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateur integer NOT NULL,
    texteavis character varying(500),
    nombreetoiles numeric(2,1) NOT NULL,
    CONSTRAINT "PK_avis" PRIMARY KEY (idavis),
    CONSTRAINT "FK_avis_annonce_idannonce" FOREIGN KEY (idannonce) REFERENCES public.annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT "FK_avis_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.favoriser (
    idutilisateur integer NOT NULL,
    idannonce integer NOT NULL,
    CONSTRAINT pk_favoriser PRIMARY KEY (idutilisateur, idannonce),
    CONSTRAINT fk_favorise_favoriser_annonce FOREIGN KEY (idannonce) REFERENCES public.annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT fk_favorise_favoriser_utilisateur FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.proposer (
    idcommodite integer NOT NULL,
    idannonce integer NOT NULL,
    CONSTRAINT pk_proposer PRIMARY KEY (idcommodite, idannonce),
    CONSTRAINT fk_proposer_proposer2_annonce FOREIGN KEY (idannonce) REFERENCES public.annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT fk_proposer_proposer_commodit FOREIGN KEY (idcommodite) REFERENCES public.commodite (idcommodite) ON DELETE CASCADE
);

CREATE TABLE public.reservation (
    idreservation integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddatedebutreservation integer NOT NULL,
    iddatefinreservation integer NOT NULL,
    idutilisateur integer NOT NULL,
    nomclient character varying(50) NOT NULL,
    prenomclient character varying(50) NOT NULL,
    telephoneclient char(10),
    CONSTRAINT "PK_reservation" PRIMARY KEY (idreservation),
    CONSTRAINT "FK_reservation_annonce_idannonce" FOREIGN KEY (idannonce) REFERENCES public.annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT "FK_reservation_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.incident (
    idincident integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idreservation integer NOT NULL,
    iddate integer NOT NULL,
    motifincident character varying(100),
    descriptionincident character varying(2000),
    etape integer NOT NULL DEFAULT 1,
    estclasse boolean NOT NULL DEFAULT FALSE,
    estrembourse boolean NOT NULL DEFAULT FALSE,
    estremisaucontentieux boolean NOT NULL DEFAULT FALSE,
    explicationproprietaire character varying(2000),
    CONSTRAINT pk_incident PRIMARY KEY (idincident),
    CONSTRAINT "FK_incident_date_iddate" FOREIGN KEY (iddate) REFERENCES public.date (iddate) ON DELETE CASCADE,
    CONSTRAINT "FK_incident_reservation_idreservation" FOREIGN KEY (idreservation) REFERENCES public.reservation (idreservation) ON DELETE CASCADE,
    CONSTRAINT "FK_incident_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE TABLE public.demander (
    idincident integer NOT NULL,
    idcompensation integer NOT NULL,
    CONSTRAINT pk_demander PRIMARY KEY (idincident, idcompensation),
    CONSTRAINT fk_demander_compensation FOREIGN KEY (idcompensation) REFERENCES public.compensation (idcompensation) ON DELETE CASCADE,
    CONSTRAINT fk_demander_incident FOREIGN KEY (idincident) REFERENCES public.incident (idincident) ON DELETE CASCADE
);

CREATE INDEX "IX_adresse_idville" ON public.adresse (idville);

CREATE INDEX "IX_annonce_idadresse" ON public.annonce (idadresse);

CREATE INDEX "IX_annonce_iddate" ON public.annonce (iddate);

CREATE INDEX "IX_annonce_idheurearrivee" ON public.annonce (idheurearrivee);

CREATE INDEX "IX_annonce_idheuredepart" ON public.annonce (idheuredepart);

CREATE INDEX "IX_annonce_idtypehebergement" ON public.annonce (idtypehebergement);

CREATE INDEX "IX_annonce_idutilisateur" ON public.annonce (idutilisateur);

CREATE INDEX "IX_avis_idannonce" ON public.avis (idannonce);

CREATE INDEX "IX_avis_idutilisateur" ON public.avis (idutilisateur);

CREATE INDEX "IX_commodite_idcategorie" ON public.commodite (idcategorie);

CREATE INDEX "IX_demander_idcompensation" ON public.demander (idcompensation);

CREATE INDEX "IX_departement_idregion" ON public.departement (idregion);

CREATE INDEX "IX_favoriser_idannonce" ON public.favoriser (idannonce);

CREATE INDEX "IX_incident_iddate" ON public.incident (iddate);

CREATE INDEX "IX_incident_idreservation" ON public.incident (idreservation);

CREATE INDEX "IX_incident_idutilisateur" ON public.incident (idutilisateur);

CREATE INDEX "IX_message_idutilisateurexpediteur" ON public.message (idutilisateurexpediteur);

CREATE INDEX "IX_message_idutilisateurreceveur" ON public.message (idutilisateurreceveur);

CREATE UNIQUE INDEX "IX_professionnel_numsiret" ON public.professionnel (numsiret);

CREATE INDEX "IX_proposer_idannonce" ON public.proposer (idannonce);

CREATE INDEX "IX_reservation_idannonce" ON public.reservation (idannonce);

CREATE INDEX "IX_reservation_idutilisateur" ON public.reservation (idutilisateur);

CREATE INDEX "IX_typehebergement_idcategorie" ON public.typehebergement (idcategorie);

CREATE INDEX "IX_utilisateur_idadresse" ON public.utilisateur (idadresse);

CREATE INDEX "IX_utilisateur_iddate" ON public.utilisateur (iddate);

CREATE UNIQUE INDEX uq_utilisateur_email ON public.utilisateur (email);

CREATE UNIQUE INDEX uq_utilisateur_telephone ON public.utilisateur (telephoneutilisateur);

CREATE INDEX "IX_ville_iddepartement" ON public.ville (iddepartement);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260311103905_migration-v1.0.0', '8.0.23');

COMMIT;

