CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AnnonceAnnonce" (
    "IdannonceA" integer NOT NULL,
    "IdannonceB" integer NOT NULL,
    CONSTRAINT "PK_AnnonceAnnonce" PRIMARY KEY ("IdannonceA", "IdannonceB")
);

CREATE TABLE "AnnonceUtilisateur" (
    "Idannonce" integer NOT NULL,
    "Idutilisateur" integer NOT NULL,
    CONSTRAINT "PK_AnnonceUtilisateur" PRIMARY KEY ("Idannonce", "Idutilisateur")
);

CREATE TABLE categorie (
    idcategorie integer GENERATED BY DEFAULT AS IDENTITY,
    nomcategorie character varying(50),
    CONSTRAINT pk_categorie PRIMARY KEY (idcategorie)
);

CREATE TABLE "CommoditeRecherche" (
    "Idcommodite" integer NOT NULL,
    "Idrecherche" integer NOT NULL,
    CONSTRAINT "PK_CommoditeRecherche" PRIMARY KEY ("Idcommodite", "Idrecherche")
);

CREATE TABLE compensation (
    idcompensation integer GENERATED BY DEFAULT AS IDENTITY,
    nomcompensation character varying(100),
    CONSTRAINT pk_compensation PRIMARY KEY (idcompensation)
);

CREATE TABLE "CompensationIncident" (
    "Idcompensation" integer NOT NULL,
    "Idincident" integer NOT NULL,
    CONSTRAINT "PK_CompensationIncident" PRIMARY KEY ("Idcompensation", "Idincident")
);

CREATE TABLE date (
    iddate integer GENERATED BY DEFAULT AS IDENTITY,
    date date,
    CONSTRAINT pk_date PRIMARY KEY (iddate)
);

CREATE TABLE heure (
    idheure integer GENERATED BY DEFAULT AS IDENTITY,
    heure time without time zone NOT NULL,
    CONSTRAINT pk_heure PRIMARY KEY (idheure)
);

CREATE TABLE permission (
    idpermission integer GENERATED BY DEFAULT AS IDENTITY,
    nompermission character varying(100),
    CONSTRAINT pk_permission PRIMARY KEY (idpermission)
);

CREATE TABLE "PermissionRole" (
    "Idpermission" integer NOT NULL,
    "Idrole" integer NOT NULL,
    CONSTRAINT "PK_PermissionRole" PRIMARY KEY ("Idpermission", "Idrole")
);

CREATE TABLE "RechercheTypehebergement" (
    "Idrecherche" integer NOT NULL,
    "Idtypehebergement" integer NOT NULL,
    CONSTRAINT "PK_RechercheTypehebergement" PRIMARY KEY ("Idrecherche", "Idtypehebergement")
);

CREATE TABLE region (
    idregion integer GENERATED BY DEFAULT AS IDENTITY,
    nomregion character varying(30) NOT NULL,
    CONSTRAINT pk_region PRIMARY KEY (idregion)
);

CREATE TABLE role (
    idrole integer GENERATED BY DEFAULT AS IDENTITY,
    nomrole character varying(100),
    CONSTRAINT pk_role PRIMARY KEY (idrole)
);

CREATE TABLE "RoleUtilisateur" (
    "Idrole" integer NOT NULL,
    "Idutilisateur" integer NOT NULL,
    CONSTRAINT "PK_RoleUtilisateur" PRIMARY KEY ("Idrole", "Idutilisateur")
);

CREATE TABLE typevoyageur (
    idtypevoyageur integer GENERATED BY DEFAULT AS IDENTITY,
    nomtypevoyageur character varying(30) NOT NULL,
    CONSTRAINT pk_typevoyageur PRIMARY KEY (idtypevoyageur)
);

CREATE TABLE commodite (
    idcommodite integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomcommodite character varying(50),
    CONSTRAINT pk_commodite PRIMARY KEY (idcommodite),
    CONSTRAINT fk_commodit_apparteni_categori FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie) ON DELETE RESTRICT
);

CREATE TABLE typehebergement (
    idtypehebergement integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomtypehebergement character varying(30),
    CONSTRAINT pk_typehebergement PRIMARY KEY (idtypehebergement),
    CONSTRAINT fk_typehebe_classer_categori FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie) ON DELETE RESTRICT
);

CREATE TABLE departement (
    iddepartement integer GENERATED BY DEFAULT AS IDENTITY,
    idregion integer NOT NULL,
    numerodepartement character varying(3),
    nomdepartement character varying(25),
    CONSTRAINT pk_departement PRIMARY KEY (iddepartement),
    CONSTRAINT fk_departem_localiser_region FOREIGN KEY (idregion) REFERENCES region (idregion) ON DELETE RESTRICT
);

CREATE TABLE permettre (
    idrole integer NOT NULL,
    idpermission integer NOT NULL,
    CONSTRAINT pk_permettre PRIMARY KEY (idrole, idpermission),
    CONSTRAINT fk_permettre_permission FOREIGN KEY (idpermission) REFERENCES permission (idpermission) ON DELETE RESTRICT,
    CONSTRAINT fk_permettre_role FOREIGN KEY (idrole) REFERENCES role (idrole) ON DELETE RESTRICT
);

CREATE TABLE ville (
    idville integer GENERATED BY DEFAULT AS IDENTITY,
    iddepartement integer NOT NULL,
    codepostal character(5) NOT NULL,
    nomville character varying(40) NOT NULL,
    taxedesejour numeric(10,2) NOT NULL,
    CONSTRAINT pk_ville PRIMARY KEY (idville),
    CONSTRAINT fk_ville_situer_departem FOREIGN KEY (iddepartement) REFERENCES departement (iddepartement) ON DELETE RESTRICT
);

CREATE TABLE adresse (
    idadresse integer GENERATED BY DEFAULT AS IDENTITY,
    idville integer NOT NULL,
    numerorue integer,
    nomrue character varying(39),
    CONSTRAINT pk_adresse PRIMARY KEY (idadresse),
    CONSTRAINT fk_adresse_posseder_ville FOREIGN KEY (idville) REFERENCES ville (idville) ON DELETE RESTRICT
);

CREATE TABLE utilisateur (
    idutilisateur integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    idtransaction integer,
    iddate integer NOT NULL,
    pseudonyme character varying(50) NOT NULL,
    email character varying(320) NOT NULL,
    email_verified_at timestamp without time zone,
    password character varying(255) NOT NULL,
    telephoneutilisateur character(10) NOT NULL,
    phone_verified boolean NOT NULL DEFAULT FALSE,
    identity_verified boolean NOT NULL DEFAULT FALSE,
    solde numeric(10,2) NOT NULL,
    remember_token character varying(100),
    two_factor_secret text,
    two_factor_recovery_codes text,
    two_factor_confirmed_at timestamp without time zone,
    profile_photo_path character varying(2048),
    CONSTRAINT pk_utilisateur PRIMARY KEY (idutilisateur),
    CONSTRAINT fk_utilisat_creer_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_utilisat_resider_adresse FOREIGN KEY (idadresse) REFERENCES adresse (idadresse) ON DELETE RESTRICT
);

CREATE TABLE annonce (
    idannonce integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    iddate integer NOT NULL,
    idheuredepart integer NOT NULL,
    idtypehebergement integer NOT NULL,
    idheurearrivee integer NOT NULL,
    idutilisateur integer NOT NULL,
    titreannonce character varying(50) NOT NULL,
    descriptionannonce character varying(4000) NOT NULL,
    nombreetoilesleboncoin integer,
    montantacompte numeric(10,2),
    pourcentageacompte integer,
    prixnuitee numeric(10,2) NOT NULL,
    capacite integer,
    nbchambres integer,
    minimumnuitee integer,
    possibiliteanimaux boolean NOT NULL,
    nombrebebesmax integer,
    possibilitefumeur boolean NOT NULL,
    estverifie boolean NOT NULL DEFAULT FALSE,
    smsverifie boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_annonce PRIMARY KEY (idannonce),
    CONSTRAINT fk_annonce_arriver_heure FOREIGN KEY (idheurearrivee) REFERENCES heure (idheure) ON DELETE RESTRICT,
    CONSTRAINT fk_annonce_diffuser_utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_annonce_partir_heure FOREIGN KEY (idheuredepart) REFERENCES heure (idheure) ON DELETE RESTRICT,
    CONSTRAINT fk_annonce_publier_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_annonce_qualifier_typehebe FOREIGN KEY (idtypehebergement) REFERENCES typehebergement (idtypehebergement) ON DELETE RESTRICT,
    CONSTRAINT fk_annonce_se_trouve_adresse FOREIGN KEY (idadresse) REFERENCES adresse (idadresse) ON DELETE RESTRICT
);

CREATE TABLE attribuer (
    idutilisateur integer NOT NULL,
    idrole integer NOT NULL,
    CONSTRAINT pk_attribuer PRIMARY KEY (idutilisateur, idrole),
    CONSTRAINT fk_attribuer_role FOREIGN KEY (idrole) REFERENCES role (idrole) ON DELETE RESTRICT,
    CONSTRAINT fk_attribuer_utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE message (
    idmessage integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateurreceveur integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateurexpediteur integer NOT NULL,
    contenumessage character varying(1000) NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (idmessage),
    CONSTRAINT fk_message_associati_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_message_expedier_utilisat FOREIGN KEY (idutilisateurexpediteur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_message_recevoir_utilisat FOREIGN KEY (idutilisateurreceveur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE particulier (
    idutilisateur integer NOT NULL,
    nomutilisateur character varying(50) NOT NULL,
    prenomutilisateur character varying(50) NOT NULL,
    civilite character varying(15) NOT NULL,
    iddate integer NOT NULL,
    CONSTRAINT pk_particulier PRIMARY KEY (idutilisateur),
    CONSTRAINT fk_particulier_heritage__utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_particulier_naitre_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT
);

CREATE TABLE professionnel (
    idutilisateur integer NOT NULL,
    numsiret numeric(14,0) NOT NULL,
    nomsociete character varying(30) NOT NULL,
    secteuractivite character varying(50) NOT NULL,
    CONSTRAINT pk_professionnel PRIMARY KEY (idutilisateur),
    CONSTRAINT fk_professionnel_heritage__utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE recherche (
    idrecherche integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idville integer,
    iddatefinrecherche integer,
    iddepartement integer,
    idregion integer,
    iddatedebutrecherche integer,
    paiementenligne boolean NOT NULL DEFAULT FALSE,
    capaciteminimumvoyageur integer,
    prixminimum numeric(10,2),
    prixmaximum numeric(10,2),
    nombreminimumchambre integer,
    nombremaximumchambre integer,
    CONSTRAINT pk_recherche PRIMARY KEY (idrecherche),
    CONSTRAINT fk_recherch_associati_utilisat FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_recherch_associer_ville FOREIGN KEY (idville) REFERENCES ville (idville) ON DELETE RESTRICT,
    CONSTRAINT fk_recherch_commencer_date FOREIGN KEY (iddatedebutrecherche) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_recherch_connecter_departem FOREIGN KEY (iddepartement) REFERENCES departement (iddepartement) ON DELETE RESTRICT,
    CONSTRAINT fk_recherch_lier_region FOREIGN KEY (idregion) REFERENCES region (idregion) ON DELETE RESTRICT,
    CONSTRAINT fk_recherch_terminer_date FOREIGN KEY (iddatefinrecherche) REFERENCES date (iddate) ON DELETE RESTRICT
);

CREATE TABLE "AnnonceCommodite" (
    "Idcommodite" integer NOT NULL,
    "Idannonce" integer NOT NULL,
    CONSTRAINT pk_proposer PRIMARY KEY ("Idcommodite", "Idannonce"),
    CONSTRAINT fk_proposer_proposer2_annonce FOREIGN KEY ("Idannonce") REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT fk_proposer_proposer_commodit FOREIGN KEY ("Idcommodite") REFERENCES commodite (idcommodite) ON DELETE RESTRICT
);

CREATE TABLE avis (
    idavis integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateur integer NOT NULL,
    texteavis character varying(500),
    nombreetoiles numeric(2,1) NOT NULL,
    CONSTRAINT pk_avis PRIMARY KEY (idavis),
    CONSTRAINT fk_avis_commenter_utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_avis_deposer_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_avis_noter_annonce FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT
);

CREATE TABLE favoriser (
    idutilisateur integer NOT NULL,
    idannonce integer NOT NULL,
    CONSTRAINT pk_favoriser PRIMARY KEY (idutilisateur, idannonce),
    CONSTRAINT fk_favorise_favoriser_annonce FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT fk_favorise_favoriser_utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE relier (
    idannonce integer NOT NULL,
    iddate integer NOT NULL,
    estdisponible boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_relier PRIMARY KEY (idannonce, iddate),
    CONSTRAINT fk_relier_relier2_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_relier_relier_annonce FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT
);

CREATE TABLE reservation (
    idreservation integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddatedebutreservation integer NOT NULL,
    iddatefinreservation integer NOT NULL,
    idutilisateur integer NOT NULL,
    nomclient character varying(50) NOT NULL,
    prenomclient character varying(50) NOT NULL,
    telephoneclient character(10),
    CONSTRAINT pk_reservation PRIMARY KEY (idreservation),
    CONSTRAINT fk_reservat_concerner_annonce FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT fk_reservat_debuter_date FOREIGN KEY (iddatedebutreservation) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_reservat_finir_date FOREIGN KEY (iddatefinreservation) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_reservation_reserver_utilisateur FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE ressembler (
    idannonce_a integer NOT NULL,
    idannonce_b integer NOT NULL,
    CONSTRAINT pk_ressembler PRIMARY KEY (idannonce_a, idannonce_b),
    CONSTRAINT fk_ressembler_idannonce_a FOREIGN KEY (idannonce_a) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT fk_ressembler_idannonce_b FOREIGN KEY (idannonce_b) REFERENCES annonce (idannonce) ON DELETE RESTRICT
);

CREATE TABLE cibler (
    idtypehebergement integer NOT NULL,
    idrecherche integer NOT NULL,
    CONSTRAINT pk_cibler PRIMARY KEY (idtypehebergement, idrecherche),
    CONSTRAINT fk_cibler_cibler2_recherch FOREIGN KEY (idrecherche) REFERENCES recherche (idrecherche) ON DELETE RESTRICT,
    CONSTRAINT fk_cibler_cibler_typehebe FOREIGN KEY (idtypehebergement) REFERENCES typehebergement (idtypehebergement) ON DELETE RESTRICT
);

CREATE TABLE filtrer (
    idrecherche integer NOT NULL,
    idcommodite integer NOT NULL,
    CONSTRAINT pk_filtrer PRIMARY KEY (idrecherche, idcommodite),
    CONSTRAINT fk_filtrer_filtrer2_commodit FOREIGN KEY (idcommodite) REFERENCES commodite (idcommodite) ON DELETE RESTRICT,
    CONSTRAINT fk_filtrer_filtrer_recherch FOREIGN KEY (idrecherche) REFERENCES recherche (idrecherche) ON DELETE RESTRICT
);

CREATE TABLE incident (
    idincident integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idreservation integer NOT NULL,
    iddate integer NOT NULL,
    motifincident character varying(100),
    descriptionincident character varying(2000),
    etape integer NOT NULL DEFAULT 1,
    estclasse boolean NOT NULL DEFAULT FALSE,
    estrembourse boolean NOT NULL DEFAULT FALSE,
    estremisaucontentieux boolean NOT NULL DEFAULT FALSE,
    explicationproprietaire character varying(2000),
    CONSTRAINT pk_incident PRIMARY KEY (idincident),
    CONSTRAINT fk_incident_associati_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_incident_associati_reservat FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT,
    CONSTRAINT fk_incident_associati_utilisat FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE inclure (
    idreservation integer NOT NULL,
    idtypevoyageur integer NOT NULL,
    nombrevoyageur integer NOT NULL DEFAULT 0,
    CONSTRAINT pk_inclure PRIMARY KEY (idreservation, idtypevoyageur),
    CONSTRAINT fk_inclure_inclure2_typevoya FOREIGN KEY (idtypevoyageur) REFERENCES typevoyageur (idtypevoyageur) ON DELETE RESTRICT,
    CONSTRAINT fk_inclure_inclure_reservat FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT
);

CREATE TABLE transaction (
    idtransaction integer GENERATED BY DEFAULT AS IDENTITY,
    iddate integer NOT NULL,
    idreservation integer NOT NULL,
    idutilisateur integer NOT NULL,
    montanttransaction numeric(10,2) NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (idtransaction),
    CONSTRAINT fk_transact_effectuer_date FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT fk_transact_faire_utilisat FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT fk_transact_regler_reservat FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT
);

CREATE TABLE demander (
    idincident integer NOT NULL,
    idcompensation integer NOT NULL,
    CONSTRAINT pk_demander PRIMARY KEY (idincident, idcompensation),
    CONSTRAINT fk_demander_compensation FOREIGN KEY (idcompensation) REFERENCES compensation (idcompensation) ON DELETE RESTRICT,
    CONSTRAINT fk_demander_incident FOREIGN KEY (idincident) REFERENCES incident (idincident) ON DELETE RESTRICT
);

CREATE TABLE photo (
    idphoto integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer,
    idincident integer,
    lienphoto character varying(200),
    CONSTRAINT pk_photo PRIMARY KEY (idphoto),
    CONSTRAINT fk_photo_comporter_annonce FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT fk_photo_prouver_incident FOREIGN KEY (idincident) REFERENCES incident (idincident) ON DELETE RESTRICT
);

CREATE INDEX idx_adresse_idville ON adresse (idville);

CREATE INDEX idx_annonce_capacite ON annonce (capacite);

CREATE INDEX idx_annonce_idadresse ON annonce (idadresse);

CREATE INDEX idx_annonce_iddate ON annonce (iddate);

CREATE INDEX idx_annonce_idheurearrivee ON annonce (idheurearrivee);

CREATE INDEX idx_annonce_idheuredepart ON annonce (idheuredepart);

CREATE INDEX idx_annonce_idtypehebergement ON annonce (idtypehebergement);

CREATE INDEX idx_annonce_idutilisateur ON annonce (idutilisateur);

CREATE INDEX idx_annonce_nbchambres ON annonce (nbchambres);

CREATE INDEX idx_annonce_prixnuitee ON annonce (prixnuitee);

CREATE INDEX idx_proposer_idannonce ON "AnnonceCommodite" ("Idannonce");

CREATE INDEX idx_proposer_idcommodite ON "AnnonceCommodite" ("Idcommodite");

CREATE INDEX "IX_attribuer_idrole" ON attribuer (idrole);

CREATE INDEX "IX_avis_idannonce" ON avis (idannonce);

CREATE INDEX "IX_avis_iddate" ON avis (iddate);

CREATE INDEX "IX_avis_idutilisateur" ON avis (idutilisateur);

CREATE INDEX idx_cibler_idrecherche ON cibler (idrecherche);

CREATE INDEX idx_commodite_idcategorie ON commodite (idcategorie);

CREATE INDEX idx_date_date ON date (date);

CREATE INDEX idx_demander_idcompensation ON demander (idcompensation);

CREATE INDEX idx_departement_idregion ON departement (idregion);

CREATE INDEX idx_favoriser_idannonce ON favoriser (idannonce);

CREATE INDEX idx_filtrer_idcommodite ON filtrer (idcommodite);

CREATE INDEX idx_incident_idreservation ON incident (idreservation);

CREATE INDEX idx_incident_idutilisateur ON incident (idutilisateur);

CREATE INDEX "IX_incident_iddate" ON incident (iddate);

CREATE INDEX idx_inclure_idtypevoyageur ON inclure (idtypevoyageur);

CREATE INDEX idx_message_idutilisateurexpediteur ON message (idutilisateurexpediteur);

CREATE INDEX idx_message_idutilisateurreceveur ON message (idutilisateurreceveur);

CREATE INDEX "IX_message_iddate" ON message (iddate);

CREATE INDEX "IX_particulier_iddate" ON particulier (iddate);

CREATE INDEX "IX_permettre_idpermission" ON permettre (idpermission);

CREATE INDEX "IX_photo_idannonce" ON photo (idannonce);

CREATE INDEX "IX_photo_idincident" ON photo (idincident);

CREATE UNIQUE INDEX professionnel_numsiret_key ON professionnel (numsiret);

CREATE INDEX "IX_recherche_iddatedebutrecherche" ON recherche (iddatedebutrecherche);

CREATE INDEX "IX_recherche_iddatefinrecherche" ON recherche (iddatefinrecherche);

CREATE INDEX "IX_recherche_iddepartement" ON recherche (iddepartement);

CREATE INDEX "IX_recherche_idregion" ON recherche (idregion);

CREATE INDEX "IX_recherche_idutilisateur" ON recherche (idutilisateur);

CREATE INDEX "IX_recherche_idville" ON recherche (idville);

CREATE UNIQUE INDEX region_nomregion_key ON region (nomregion);

CREATE INDEX idx_relier_iddate ON relier (iddate);

CREATE INDEX idx_reservation_idannonce ON reservation (idannonce);

CREATE INDEX idx_reservation_iddatedebutres ON reservation (iddatedebutreservation);

CREATE INDEX idx_reservation_iddatefinres ON reservation (iddatefinreservation);

CREATE INDEX idx_reservation_idutilisateur ON reservation (idutilisateur);

CREATE INDEX idx_ressembler_idannonce_b ON ressembler (idannonce_b);

CREATE INDEX idx_transaction_iddate ON transaction (iddate);

CREATE INDEX idx_transaction_idreservation ON transaction (idreservation);

CREATE INDEX idx_transaction_idutilisateur ON transaction (idutilisateur);

CREATE INDEX idx_typehebergement_idcategorie ON typehebergement (idcategorie);

CREATE UNIQUE INDEX typevoyageur_nomtypevoyageur_key ON typevoyageur (nomtypevoyageur);

CREATE INDEX idx_utilisateur_idadresse ON utilisateur (idadresse);

CREATE INDEX idx_utilisateur_iddate ON utilisateur (iddate);

CREATE INDEX idx_utilisateur_idtransaction ON utilisateur (idtransaction);

CREATE UNIQUE INDEX utilisateur_email_key ON utilisateur (email);

CREATE UNIQUE INDEX utilisateur_telephoneutilisateur_key ON utilisateur (telephoneutilisateur);

CREATE INDEX idx_ville_iddepartement ON ville (iddepartement);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260324164253_migration-v1.0.0', '8.0.23');

COMMIT;

START TRANSACTION;

CREATE TABLE statutdemande (
    idstatut integer GENERATED BY DEFAULT AS IDENTITY,
    nomstatut character varying(50) NOT NULL,
    CONSTRAINT "PK_statutdemande" PRIMARY KEY (idstatut)
);

CREATE TABLE demandesuppressioncompte (
    iddemande integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idstatut integer NOT NULL,
    datedemande timestamp without time zone NOT NULL,
    motifrefus character varying(500),
    CONSTRAINT "PK_demandesuppressioncompte" PRIMARY KEY (iddemande),
    CONSTRAINT "FK_demandesuppressioncompte_statutdemande_idstatut" FOREIGN KEY (idstatut) REFERENCES statutdemande (idstatut) ON DELETE CASCADE,
    CONSTRAINT "FK_demandesuppressioncompte_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE CASCADE
);

CREATE INDEX "IX_demandesuppressioncompte_idstatut" ON demandesuppressioncompte (idstatut);

CREATE INDEX "IX_demandesuppressioncompte_idutilisateur" ON demandesuppressioncompte (idutilisateur);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325005551_migration-v1.0.1', '8.0.23');

COMMIT;

START TRANSACTION;

ALTER TABLE incident DROP COLUMN estclasse;

ALTER TABLE incident DROP COLUMN estrembourse;

ALTER TABLE incident DROP COLUMN estremisaucontentieux;

CREATE TABLE statut_incident (
    idstatutincident integer GENERATED BY DEFAULT AS IDENTITY,
    code character varying(60) NOT NULL,
    libelle character varying(120) NOT NULL,
    ordre integer NOT NULL,
    estfinal boolean NOT NULL,
    CONSTRAINT pk_statut_incident PRIMARY KEY (idstatutincident)
);

INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (1, 'SIGNALE', FALSE, 'Signale', 1);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (2, 'EN_ANALYSE_SERVICE_LOCATION', FALSE, 'En cours d''analyse par le service location', 2);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (3, 'CLASSE_SANS_SUITE', TRUE, 'Classe sans suite', 3);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (4, 'EN_ATTENTE_EXPLICATION_PROPRIETAIRE', FALSE, 'En attente de l''explication du proprietaire', 4);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (5, 'EXPLICATION_PROPRIETAIRE_RECUE', FALSE, 'Explication du proprietaire recue', 5);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (6, 'REMBOURSEMENT_ACCEPTE', FALSE, 'Remboursement accepte', 6);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (7, 'REFUS_REMBOURSEMENT', FALSE, 'Remboursement refuse', 7);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (9, 'TRANSFERE_CONTENTIEUX', FALSE, 'Transfere au contentieux', 8);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (10, 'CLOTURE_SANS_REMBOURSEMENT', TRUE, 'Cloture sans remboursement', 9);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (11, 'PROCEDURE_JURIDIQUE_ENGAGEE', TRUE, 'Procedure juridique engagee', 10);
INSERT INTO statut_incident (idstatutincident, code, estfinal, libelle, ordre)
VALUES (12, 'REMBOURSEMENT_EFFECTUE', TRUE, 'Remboursement effectue', 11);

ALTER TABLE incident ADD idstatutincident integer NOT NULL DEFAULT 1;

UPDATE incident SET idstatutincident = 1 WHERE idstatutincident IS NULL OR idstatutincident = 0;

ALTER TABLE incident DROP COLUMN etape;

CREATE INDEX idx_incident_idstatutincident ON incident (idstatutincident);

CREATE UNIQUE INDEX uq_statut_incident_code ON statut_incident (code);

ALTER TABLE incident ADD CONSTRAINT fk_incident_statut_incident FOREIGN KEY (idstatutincident) REFERENCES statut_incident (idstatutincident) ON DELETE RESTRICT;

SELECT setval(
    pg_get_serial_sequence('statut_incident', 'idstatutincident'),
    GREATEST(
        (SELECT MAX(idstatutincident) FROM statut_incident) + 1,
        nextval(pg_get_serial_sequence('statut_incident', 'idstatutincident'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325040814_AddStatutIncident', '8.0.23');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260325041125_migration-v1.0.2', '8.0.23');

COMMIT;

