CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE categorie (
    idcategorie integer GENERATED BY DEFAULT AS IDENTITY,
    nomcategorie character varying(50),
    CONSTRAINT "PK_categorie" PRIMARY KEY (idcategorie)
);

CREATE TABLE compensation (
    idcompensation integer GENERATED BY DEFAULT AS IDENTITY,
    nomcompensation character varying(100),
    CONSTRAINT "PK_compensation" PRIMARY KEY (idcompensation)
);

CREATE TABLE date (
    iddate integer GENERATED BY DEFAULT AS IDENTITY,
    date date,
    CONSTRAINT "PK_date" PRIMARY KEY (iddate)
);

CREATE TABLE heure (
    idheure integer GENERATED BY DEFAULT AS IDENTITY,
    heure time without time zone NOT NULL,
    CONSTRAINT "PK_heure" PRIMARY KEY (idheure)
);

CREATE TABLE permission (
    idpermission integer GENERATED BY DEFAULT AS IDENTITY,
    nompermission character varying(100),
    CONSTRAINT "PK_permission" PRIMARY KEY (idpermission)
);

CREATE TABLE region (
    idregion integer GENERATED BY DEFAULT AS IDENTITY,
    nomregion character varying(30) NOT NULL,
    CONSTRAINT "PK_region" PRIMARY KEY (idregion)
);

CREATE TABLE role (
    idrole integer GENERATED BY DEFAULT AS IDENTITY,
    nomrole character varying(100),
    CONSTRAINT "PK_role" PRIMARY KEY (idrole)
);

CREATE TABLE typevoyageur (
    idtypevoyageur integer GENERATED BY DEFAULT AS IDENTITY,
    nomtypevoyageur character varying(30) NOT NULL,
    CONSTRAINT "PK_typevoyageur" PRIMARY KEY (idtypevoyageur)
);

CREATE TABLE commodite (
    idcommodite integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomcommodite character varying(50),
    CONSTRAINT "PK_commodite" PRIMARY KEY (idcommodite),
    CONSTRAINT "FK_commodite_categorie_idcategorie" FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie) ON DELETE RESTRICT
);

CREATE TABLE typehebergement (
    idtypehebergement integer GENERATED BY DEFAULT AS IDENTITY,
    idcategorie integer NOT NULL,
    nomtypehebergement character varying(30),
    CONSTRAINT "PK_typehebergement" PRIMARY KEY (idtypehebergement),
    CONSTRAINT "FK_typehebergement_categorie_idcategorie" FOREIGN KEY (idcategorie) REFERENCES categorie (idcategorie) ON DELETE RESTRICT
);

CREATE TABLE departement (
    iddepartement integer GENERATED BY DEFAULT AS IDENTITY,
    idregion integer NOT NULL,
    numerodepartement character varying(3),
    nomdepartement character varying(25),
    CONSTRAINT "PK_departement" PRIMARY KEY (iddepartement),
    CONSTRAINT "FK_departement_region_idregion" FOREIGN KEY (idregion) REFERENCES region (idregion) ON DELETE RESTRICT
);

CREATE TABLE permettre (
    "Idpermission" integer NOT NULL,
    "Idrole" integer NOT NULL,
    CONSTRAINT "PK_permettre" PRIMARY KEY ("Idpermission", "Idrole"),
    CONSTRAINT "FK_permettre_permission_Idpermission" FOREIGN KEY ("Idpermission") REFERENCES permission (idpermission) ON DELETE CASCADE,
    CONSTRAINT "FK_permettre_role_Idrole" FOREIGN KEY ("Idrole") REFERENCES role (idrole) ON DELETE CASCADE
);

CREATE TABLE ville (
    idville integer GENERATED BY DEFAULT AS IDENTITY,
    iddepartement integer NOT NULL,
    codepostal character varying(5) NOT NULL,
    nomville character varying(40) NOT NULL,
    taxedesejour numeric(10,2) NOT NULL,
    CONSTRAINT "PK_ville" PRIMARY KEY (idville),
    CONSTRAINT "FK_ville_departement_iddepartement" FOREIGN KEY (iddepartement) REFERENCES departement (iddepartement) ON DELETE RESTRICT
);

CREATE TABLE adresse (
    idadresse integer GENERATED BY DEFAULT AS IDENTITY,
    idville integer NOT NULL,
    numerorue integer,
    nomrue character varying(39),
    CONSTRAINT "PK_adresse" PRIMARY KEY (idadresse),
    CONSTRAINT "FK_adresse_ville_idville" FOREIGN KEY (idville) REFERENCES ville (idville) ON DELETE CASCADE
);

CREATE TABLE annonce (
    idannonce integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    iddate integer NOT NULL,
    idheuredepart integer NOT NULL,
    idtypehebergement integer NOT NULL,
    idheurearrivee integer NOT NULL,
    idutilisateur integer NOT NULL,
    titreannonce character varying(50) NOT NULL,
    descriptionannonce character varying(4000) NOT NULL,
    lienphoto character varying(200),
    nombreetoilesleboncoin integer,
    montantacompte numeric(10,2),
    pourcentageacompte integer,
    prixnuitee numeric(10,2) NOT NULL,
    capacite integer,
    nbchambres integer,
    minimumnuitee integer,
    possibiliteanimaux boolean NOT NULL,
    nombrebebesmax integer,
    possibilitefumeur boolean NOT NULL,
    estverifie boolean NOT NULL,
    smsverifie boolean NOT NULL,
    CONSTRAINT "PK_annonce" PRIMARY KEY (idannonce),
    CONSTRAINT "FK_annonce_adresse_idadresse" FOREIGN KEY (idadresse) REFERENCES adresse (idadresse) ON DELETE RESTRICT,
    CONSTRAINT "FK_annonce_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_annonce_heure_idheurearrivee" FOREIGN KEY (idheurearrivee) REFERENCES heure (idheure) ON DELETE RESTRICT,
    CONSTRAINT "FK_annonce_heure_idheuredepart" FOREIGN KEY (idheuredepart) REFERENCES heure (idheure) ON DELETE RESTRICT,
    CONSTRAINT "FK_annonce_typehebergement_idtypehebergement" FOREIGN KEY (idtypehebergement) REFERENCES typehebergement (idtypehebergement) ON DELETE RESTRICT
);

CREATE TABLE "AnnonceCommodite" (
    "Idannonce" integer NOT NULL,
    "Idcommodite" integer NOT NULL,
    CONSTRAINT "PK_AnnonceCommodite" PRIMARY KEY ("Idannonce", "Idcommodite"),
    CONSTRAINT "FK_AnnonceCommodite_annonce_Idannonce" FOREIGN KEY ("Idannonce") REFERENCES annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT "FK_AnnonceCommodite_commodite_Idcommodite" FOREIGN KEY ("Idcommodite") REFERENCES commodite (idcommodite) ON DELETE CASCADE
);

CREATE TABLE relier (
    idannonce integer NOT NULL,
    iddate integer NOT NULL,
    estdisponible boolean NOT NULL,
    CONSTRAINT "PK_relier" PRIMARY KEY (idannonce, iddate),
    CONSTRAINT "FK_relier_annonce_idannonce" FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT "FK_relier_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT
);

CREATE TABLE ressembler (
    "IdannonceA" integer NOT NULL,
    "IdannonceB" integer NOT NULL,
    CONSTRAINT "PK_ressembler" PRIMARY KEY ("IdannonceA", "IdannonceB"),
    CONSTRAINT "FK_ressembler_annonce_IdannonceA" FOREIGN KEY ("IdannonceA") REFERENCES annonce (idannonce) ON DELETE CASCADE,
    CONSTRAINT "FK_ressembler_annonce_IdannonceB" FOREIGN KEY ("IdannonceB") REFERENCES annonce (idannonce) ON DELETE CASCADE
);

CREATE TABLE "AnnonceUtilisateur" (
    "Idannonce" integer NOT NULL,
    "Idutilisateur" integer NOT NULL,
    CONSTRAINT "PK_AnnonceUtilisateur" PRIMARY KEY ("Idannonce", "Idutilisateur"),
    CONSTRAINT "FK_AnnonceUtilisateur_annonce_Idannonce" FOREIGN KEY ("Idannonce") REFERENCES annonce (idannonce) ON DELETE CASCADE
);

CREATE TABLE attribuer (
    "Idrole" integer NOT NULL,
    "Idutilisateur" integer NOT NULL,
    CONSTRAINT "PK_attribuer" PRIMARY KEY ("Idrole", "Idutilisateur"),
    CONSTRAINT "FK_attribuer_role_Idrole" FOREIGN KEY ("Idrole") REFERENCES role (idrole) ON DELETE CASCADE
);

CREATE TABLE avis (
    idavis integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateur integer NOT NULL,
    texteavis character varying(500),
    nombreetoiles numeric(2,1) NOT NULL,
    CONSTRAINT "PK_avis" PRIMARY KEY (idavis),
    CONSTRAINT "FK_avis_annonce_idannonce" FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT "FK_avis_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT
);

CREATE TABLE cartebancaire (
    idcartebancaire integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    nomtitulaire character varying(50),
    prenomtitulaire character varying(50),
    numerocartebancaire numeric(16,0),
    dateexpiration date,
    numerocvv numeric(3,0),
    CONSTRAINT "PK_cartebancaire" PRIMARY KEY (idcartebancaire)
);

CREATE TABLE utilisateur (
    idutilisateur integer GENERATED BY DEFAULT AS IDENTITY,
    idadresse integer NOT NULL,
    idcartebancaire integer,
    iddate integer NOT NULL,
    pseudonyme character varying(50) NOT NULL,
    email character varying(320) NOT NULL,
    email_verified_at timestamp without time zone,
    password character varying(255) NOT NULL,
    telephoneutilisateur character varying(10) NOT NULL,
    phone_verified boolean NOT NULL,
    identity_verified boolean NOT NULL,
    solde numeric(10,2) NOT NULL,
    remember_token character varying(100),
    two_factor_secret text,
    two_factor_recovery_codes text,
    two_factor_confirmed_at timestamp without time zone,
    profile_photo_path character varying(2048),
    CONSTRAINT "PK_utilisateur" PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_utilisateur_adresse_idadresse" FOREIGN KEY (idadresse) REFERENCES adresse (idadresse) ON DELETE RESTRICT,
    CONSTRAINT "FK_utilisateur_cartebancaire_idcartebancaire" FOREIGN KEY (idcartebancaire) REFERENCES cartebancaire (idcartebancaire) ON DELETE RESTRICT,
    CONSTRAINT "FK_utilisateur_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT
);

CREATE TABLE message (
    idmessage integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateurreceveur integer NOT NULL,
    iddate integer NOT NULL,
    idutilisateurexpediteur integer NOT NULL,
    contenumessage character varying(1000) NOT NULL,
    CONSTRAINT "PK_message" PRIMARY KEY (idmessage),
    CONSTRAINT "FK_message_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_message_utilisateur_idutilisateurexpediteur" FOREIGN KEY (idutilisateurexpediteur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT "FK_message_utilisateur_idutilisateurreceveur" FOREIGN KEY (idutilisateurreceveur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE particulier (
    idutilisateur integer NOT NULL,
    nomutilisateur character varying(50) NOT NULL,
    prenomutilisateur character varying(50) NOT NULL,
    civilite character varying(15) NOT NULL,
    iddate integer NOT NULL,
    CONSTRAINT "PK_particulier" PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_particulier_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_particulier_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE professionnel (
    idutilisateur integer NOT NULL,
    numsiret numeric(14,0) NOT NULL,
    nomsociete character varying(30) NOT NULL,
    secteuractivite character varying(50) NOT NULL,
    CONSTRAINT "PK_professionnel" PRIMARY KEY (idutilisateur),
    CONSTRAINT "FK_professionnel_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE recherche (
    idrecherche integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idville integer,
    iddatefinrecherche integer,
    iddepartement integer,
    idregion integer,
    iddatedebutrecherche integer,
    paiementenligne boolean NOT NULL,
    capaciteminimumvoyageur integer,
    prixminimum numeric(10,2),
    prixmaximum numeric(10,2),
    nombreminimumchambre integer,
    nombremaximumchambre integer,
    CONSTRAINT "PK_recherche" PRIMARY KEY (idrecherche),
    CONSTRAINT "FK_recherche_date_iddatedebutrecherche" FOREIGN KEY (iddatedebutrecherche) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_recherche_date_iddatefinrecherche" FOREIGN KEY (iddatefinrecherche) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_recherche_departement_iddepartement" FOREIGN KEY (iddepartement) REFERENCES departement (iddepartement) ON DELETE RESTRICT,
    CONSTRAINT "FK_recherche_region_idregion" FOREIGN KEY (idregion) REFERENCES region (idregion) ON DELETE RESTRICT,
    CONSTRAINT "FK_recherche_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT,
    CONSTRAINT "FK_recherche_ville_idville" FOREIGN KEY (idville) REFERENCES ville (idville) ON DELETE RESTRICT
);

CREATE TABLE reservation (
    idreservation integer GENERATED BY DEFAULT AS IDENTITY,
    idannonce integer NOT NULL,
    iddatedebutreservation integer NOT NULL,
    iddatefinreservation integer NOT NULL,
    idutilisateur integer NOT NULL,
    nomclient character varying(50) NOT NULL,
    prenomclient character varying(50) NOT NULL,
    telephoneclient character varying(10),
    CONSTRAINT "PK_reservation" PRIMARY KEY (idreservation),
    CONSTRAINT "FK_reservation_annonce_idannonce" FOREIGN KEY (idannonce) REFERENCES annonce (idannonce) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_date_iddatedebutreservation" FOREIGN KEY (iddatedebutreservation) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_date_iddatefinreservation" FOREIGN KEY (iddatefinreservation) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_reservation_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE cibler (
    "Idrecherche" integer NOT NULL,
    "Idtypehebergement" integer NOT NULL,
    CONSTRAINT "PK_cibler" PRIMARY KEY ("Idrecherche", "Idtypehebergement"),
    CONSTRAINT "FK_cibler_recherche_Idrecherche" FOREIGN KEY ("Idrecherche") REFERENCES recherche (idrecherche) ON DELETE CASCADE,
    CONSTRAINT "FK_cibler_typehebergement_Idtypehebergement" FOREIGN KEY ("Idtypehebergement") REFERENCES typehebergement (idtypehebergement) ON DELETE CASCADE
);

CREATE TABLE filtrer (
    "Idcommodite" integer NOT NULL,
    "Idrecherche" integer NOT NULL,
    CONSTRAINT "PK_filtrer" PRIMARY KEY ("Idcommodite", "Idrecherche"),
    CONSTRAINT "FK_filtrer_commodite_Idcommodite" FOREIGN KEY ("Idcommodite") REFERENCES commodite (idcommodite) ON DELETE CASCADE,
    CONSTRAINT "FK_filtrer_recherche_Idrecherche" FOREIGN KEY ("Idrecherche") REFERENCES recherche (idrecherche) ON DELETE CASCADE
);

CREATE TABLE incident (
    idincident integer GENERATED BY DEFAULT AS IDENTITY,
    idutilisateur integer NOT NULL,
    idreservation integer NOT NULL,
    iddate integer NOT NULL,
    motifincident character varying(100),
    descriptionincident character varying(2000),
    lienphotoincident character varying(200),
    etape integer,
    estclasse boolean,
    estrembourse boolean,
    estremisaucontentieux boolean,
    explicationproprietaire character varying(2000),
    CONSTRAINT "PK_incident" PRIMARY KEY (idincident),
    CONSTRAINT "FK_incident_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_incident_reservation_idreservation" FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT,
    CONSTRAINT "FK_incident_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT
);

CREATE TABLE inclure (
    idreservation integer NOT NULL,
    idtypevoyageur integer NOT NULL,
    nombrevoyageur integer NOT NULL,
    CONSTRAINT "PK_inclure" PRIMARY KEY (idreservation, idtypevoyageur),
    CONSTRAINT "FK_inclure_reservation_idreservation" FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT,
    CONSTRAINT "FK_inclure_typevoyageur_idtypevoyageur" FOREIGN KEY (idtypevoyageur) REFERENCES typevoyageur (idtypevoyageur) ON DELETE RESTRICT
);

CREATE TABLE transaction (
    idtransaction integer GENERATED BY DEFAULT AS IDENTITY,
    iddate integer NOT NULL,
    idreservation integer NOT NULL,
    idcartebancaire integer NOT NULL,
    montanttransaction numeric(10,2) NOT NULL,
    CONSTRAINT "PK_transaction" PRIMARY KEY (idtransaction),
    CONSTRAINT "FK_transaction_cartebancaire_idcartebancaire" FOREIGN KEY (idcartebancaire) REFERENCES cartebancaire (idcartebancaire) ON DELETE RESTRICT,
    CONSTRAINT "FK_transaction_date_iddate" FOREIGN KEY (iddate) REFERENCES date (iddate) ON DELETE RESTRICT,
    CONSTRAINT "FK_transaction_reservation_idreservation" FOREIGN KEY (idreservation) REFERENCES reservation (idreservation) ON DELETE RESTRICT
);

CREATE TABLE demander (
    "Idcompensation" integer NOT NULL,
    "Idincident" integer NOT NULL,
    CONSTRAINT "PK_demander" PRIMARY KEY ("Idcompensation", "Idincident"),
    CONSTRAINT "FK_demander_compensation_Idcompensation" FOREIGN KEY ("Idcompensation") REFERENCES compensation (idcompensation) ON DELETE CASCADE,
    CONSTRAINT "FK_demander_incident_Idincident" FOREIGN KEY ("Idincident") REFERENCES incident (idincident) ON DELETE CASCADE
);

CREATE INDEX idx_adresse_idville ON adresse (idville);

CREATE INDEX idx_annonce_capacite ON annonce (capacite);

CREATE INDEX idx_annonce_idadresse ON annonce (idadresse);

CREATE INDEX idx_annonce_iddate ON annonce (iddate);

CREATE INDEX idx_annonce_idheurearrivee ON annonce (idheurearrivee);

CREATE INDEX idx_annonce_idheuredepart ON annonce (idheuredepart);

CREATE INDEX idx_annonce_idtypehebergement ON annonce (idtypehebergement);

CREATE INDEX idx_annonce_idutilisateur ON annonce (idutilisateur);

CREATE INDEX idx_annonce_nbchambres ON annonce (nbchambres);

CREATE INDEX idx_annonce_prixnuitee ON annonce (prixnuitee);

CREATE INDEX "IX_AnnonceCommodite_Idcommodite" ON "AnnonceCommodite" ("Idcommodite");

CREATE INDEX "IX_AnnonceUtilisateur_Idutilisateur" ON "AnnonceUtilisateur" ("Idutilisateur");

CREATE INDEX "IX_attribuer_Idutilisateur" ON attribuer ("Idutilisateur");

CREATE INDEX "IX_avis_idannonce" ON avis (idannonce);

CREATE INDEX "IX_avis_iddate" ON avis (iddate);

CREATE INDEX "IX_avis_idutilisateur" ON avis (idutilisateur);

CREATE INDEX "IX_cartebancaire_idutilisateur" ON cartebancaire (idutilisateur);

CREATE INDEX "IX_cibler_Idtypehebergement" ON cibler ("Idtypehebergement");

CREATE INDEX idx_commodite_idcategorie ON commodite (idcategorie);

CREATE INDEX idx_date_date ON date (date);

CREATE INDEX "IX_demander_Idincident" ON demander ("Idincident");

CREATE INDEX idx_departement_idregion ON departement (idregion);

CREATE INDEX "IX_filtrer_Idrecherche" ON filtrer ("Idrecherche");

CREATE INDEX idx_incident_idreservation ON incident (idreservation);

CREATE INDEX idx_incident_idutilisateur ON incident (idutilisateur);

CREATE INDEX "IX_incident_iddate" ON incident (iddate);

CREATE INDEX idx_inclure_idtypevoyageur ON inclure (idtypevoyageur);

CREATE INDEX idx_message_idutilisateurexpediteur ON message (idutilisateurexpediteur);

CREATE INDEX idx_message_idutilisateurreceveur ON message (idutilisateurreceveur);

CREATE INDEX "IX_message_iddate" ON message (iddate);

CREATE INDEX "IX_particulier_iddate" ON particulier (iddate);

CREATE INDEX "IX_permettre_Idrole" ON permettre ("Idrole");

CREATE UNIQUE INDEX professionnel_numsiret_key ON professionnel (numsiret);

CREATE INDEX "IX_recherche_iddatedebutrecherche" ON recherche (iddatedebutrecherche);

CREATE INDEX "IX_recherche_iddatefinrecherche" ON recherche (iddatefinrecherche);

CREATE INDEX "IX_recherche_iddepartement" ON recherche (iddepartement);

CREATE INDEX "IX_recherche_idregion" ON recherche (idregion);

CREATE INDEX "IX_recherche_idutilisateur" ON recherche (idutilisateur);

CREATE INDEX "IX_recherche_idville" ON recherche (idville);

CREATE UNIQUE INDEX region_nomregion_key ON region (nomregion);

CREATE INDEX idx_relier_iddate ON relier (iddate);

CREATE INDEX idx_reservation_idannonce ON reservation (idannonce);

CREATE INDEX idx_reservation_iddatedebutres ON reservation (iddatedebutreservation);

CREATE INDEX idx_reservation_iddatefinres ON reservation (iddatefinreservation);

CREATE INDEX idx_reservation_idutilisateur ON reservation (idutilisateur);

CREATE INDEX "IX_ressembler_IdannonceB" ON ressembler ("IdannonceB");

CREATE INDEX idx_transaction_idcartebancaire ON transaction (idcartebancaire);

CREATE INDEX idx_transaction_iddate ON transaction (iddate);

CREATE INDEX idx_transaction_idreservation ON transaction (idreservation);

CREATE INDEX idx_typehebergement_idcategorie ON typehebergement (idcategorie);

CREATE UNIQUE INDEX typevoyageur_nomtypevoyageur_key ON typevoyageur (nomtypevoyageur);

CREATE INDEX idx_utilisateur_idadresse ON utilisateur (idadresse);

CREATE INDEX idx_utilisateur_idcartebancaire ON utilisateur (idcartebancaire);

CREATE INDEX idx_utilisateur_iddate ON utilisateur (iddate);

CREATE UNIQUE INDEX utilisateur_email_key ON utilisateur (email);

CREATE UNIQUE INDEX utilisateur_telephoneutilisateur_key ON utilisateur (telephoneutilisateur);

CREATE INDEX idx_ville_iddepartement ON ville (iddepartement);

ALTER TABLE annonce ADD CONSTRAINT "FK_annonce_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT;

ALTER TABLE "AnnonceUtilisateur" ADD CONSTRAINT "FK_AnnonceUtilisateur_utilisateur_Idutilisateur" FOREIGN KEY ("Idutilisateur") REFERENCES utilisateur (idutilisateur) ON DELETE CASCADE;

ALTER TABLE attribuer ADD CONSTRAINT "FK_attribuer_utilisateur_Idutilisateur" FOREIGN KEY ("Idutilisateur") REFERENCES utilisateur (idutilisateur) ON DELETE CASCADE;

ALTER TABLE avis ADD CONSTRAINT "FK_avis_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT;

ALTER TABLE cartebancaire ADD CONSTRAINT "FK_cartebancaire_utilisateur_idutilisateur" FOREIGN KEY (idutilisateur) REFERENCES utilisateur (idutilisateur) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260312140947_migration-v1.0.0', '8.0.23');

COMMIT;

START TRANSACTION;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260314162338_migration-v1.0.1', '8.0.23');

COMMIT;

